Repository openshift-eng/art-tools, pull requests merged in 2023-11, with the labels that each got.

#149 Advisory id should be passed as string
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#150 Fix liveID verification
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#151 Fix advisory-images command
  elliott/elliottlib/errata.py
  elliott/tests/test_errata.py
Labels: approved, lgtm

#155 Update release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/tests/cli/test_gen_assembly.py
Labels: approved, lgtm

#154 [ART-7678] stop building microshift 4.13
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#153 Update art-tools packaging
  Makefile
  artcommon/artcommonlib/__init__.py
  artcommon/artcommonlib/constants.py
  artcommon/artcommonlib/model.py
  artcommon/artcommonlib/rhcos.py
  artcommon/artcommonlib/runtime.py
  artcommon/setup.py
  doozer/artcommon
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/detect_embargo.py
  doozer/doozerlib/cli/gen_assembly_helper.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/model.py
  doozer/doozerlib/rhcos.py
  doozer/doozerlib/runtime.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/test_rhcos.py
  elliott/artcommon
  elliott/elliottlib/cli/rhcos_cli.py
  elliott/elliottlib/constants.py
  elliott/elliottlib/model.py
  elliott/elliottlib/rhcos.py
  elliott/elliottlib/runtime.py
  install.sh
  pyartcd/artcommon
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/runtime.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#108 Add experimental distributed tracing with OpenTelemetry
  doozer/doozerlib/assembly.py
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/telemetry.py
  doozer/requirements.txt
  pyartcd/pyartcd/cli.py
  pyartcd/pyartcd/exectools.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/telemetry.py
  pyartcd/requirements.txt
Labels: approved, lgtm

#157 ART-3506 Do not limit rebase into -priv to one component
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#158 Add missing -e to install.sh
  install.sh
Labels: lgtm

#146 ART-7990: Improve wording about blocker bug messages
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  pyartcd/pyartcd/pipelines/check_bugs.py
Labels: approved, lgtm, jira/valid-reference

#159 ART-8188: Deal with missing containerfile
  doozer/doozerlib/distgit.py
Labels: approved, lgtm, jira/valid-reference

#156 ART-8187 check blocking advisory when drop advisory
  elliott/elliottlib/cli/advisory_drop_cli.py
  elliott/elliottlib/errata.py
Labels: approved, lgtm

#161 changed log severity level
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#160 ART-5914 Trigger-build-sync-automatically after gen-assembly
  Makefile
  artcommon/artcommonlib/util.py
  artcommon/tests/__init__.py
  artcommon/tests/test_util.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/util.py
  doozer/tests/test_distgit/test_convert_source_url_to_https.py
  doozer/tests/test_util.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
  pyartcd/tests/pipelines/test_gen_assembly.py
Labels: lgtm

#164 Remove unused --debug flag
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#162 [ART-6149] Fix comment on PR feature
  doozer/doozerlib/comment_on_pr.py
  doozer/doozerlib/distgit.py
  doozer/tests/test_comment_on_pr.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: approved, lgtm

#165 fix comment arg
  pyartcd/pyartcd/jenkins.py
Labels: approved, lgtm

#166 Add a retry when trying to update nightly imagestreams
  doozer/doozerlib/cli/release_gen_payload.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#167 [ART-8113] elliott: enable prerelease/advance/bootimage advisories
  elliott/elliottlib/constants.py
Labels: approved, lgtm

#170 Comment on source PR only for stream
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#172 Fix microshift-sync link in slack
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#148 ART-7731 use actual advisroy type for release
  elliott/elliottlib/cli/create_cli.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#141 [ART-7926] Create OCPBUGS tickets to track vulnerabilities
  doozer/doozerlib/cli/scan_osh.py
  pyartcd/pyartcd/pipelines/brew_scan_osh.py
Labels: approved, lgtm

#175 Adding art-dash link to promote email
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#176 Skip when no nvrs to scan
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#177 Do not clean signing advisories if signing is not needed
  doozer/doozerlib/cli/config_plashet.py
Labels: approved, lgtm

#178 [scan-osh] Add version to title
  pyartcd/pyartcd/pipelines/brew_scan_osh.py
Labels: approved, lgtm

#183 [scan-osh] Fix nvr bug
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#190 [scan-osh] Update only description when there is a new build
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#194 [scan-osh] Update OCPBUGS workflow run
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#196 [scan-osh] match ocp-build-data config
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#195 Prevent rebuild when scanning config changes
  doozer/doozerlib/image.py
Labels: approved, lgtm

#197 [scan-osh] time out component, if can't find successful scan
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#198 [scan-osh] Skip component if can't file imp file
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#201 Use new target version field
  doozer/doozerlib/cli/images_streams.py
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#200 doozer config:read-assembly remove redundant param "assembly"
  doozer/doozerlib/cli/__main__.py
  pyartcd/pyartcd/util.py
Labels: lgtm

#202 Revert "[ART-7056] deprecate placeholder bug"
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/cli/create_placeholder_cli.py
  elliott/elliottlib/cli/create_textonly_cli.py
  elliott/elliottlib/cli/repair_bugs_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/functional_tests/test_verify_attached_bugs.py
  elliott/tests/test_bzutil.py
  elliott/tests/test_repair_bugs_cli.py
  pyartcd/pyartcd/pipelines/advisory_drop.py
Labels: approved, lgtm

#206 bug sweep: look more precise at cutoff event
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#207 ART-8309: Skip PR build notifier reporting on old PR
  doozer/doozerlib/comment_on_pr.py
  doozer/tests/test_comment_on_pr.py
Labels: approved, lgtm, jira/valid-reference

#212 reconcile jira earlier for new pr
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#211 Include disabled rpms flag for rpms:print
  doozer/doozerlib/cli/rpms.py
Labels: approved, lgtm

#210 Refactor doozer rpms: commands to rpms.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/cli/rpms_build.py
  doozer/tests/cli/test_rpms_build.py
Labels: approved, lgtm

#214 [scan-osh] Comment on bugs ticket with scan urls
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#217 ART-8413 Exact jira title search
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm
