Repository openshift-eng/art-tools, pull requests merged in 2023-08, with the labels that each got.

#7 Update OWNERS files
  doozer/OWNERS
  doozer/doozerlib/cli/ci_transforms/rhel-8/ci-build-root/OWNERS
  doozer/doozerlib/cli/ci_transforms/rhel-9/ci-build-root/OWNERS
  elliott/OWNERS
Labels: approved, lgtm

#8 [ART-7412] Update CI
  .github/workflows/doozer-unit-tests.yaml
  .github/workflows/elliott-unit-tests.yaml
  doozer/.github/workflows/snyk_security.yaml
  elliott/.github/workflows/snyk_security.yaml
Labels: approved, lgtm

#12 [ART-7462] set alignment bug's depends
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#15 Fix target_release key fetch
  doozer/doozerlib/cli/images_streams.py
Labels: lgtm

#18 [ART-7273] add go wrapper script in doozer
  doozer/doozerlib/golang_builder_FIPS_wrapper.sh
  doozer/doozerlib/source_modifications.py
Labels: approved, lgtm

#11 [ART-4761] mirror builder image streams of ocp-private namespace
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#19 mass-rebuilds: only for streams.<stream>.image attribute
  doozer/doozerlib/image.py
Labels: approved, lgtm, do-not-merge/hold

#20 Revert "mass-rebuilds: only for streams.<stream>.image attribute"
  doozer/doozerlib/image.py
Labels: approved, lgtm

#22 [ART-7318][ART-5526] introduce doozer operator_index_mode for pre-releases
  doozer/.devcontainer/dev.Dockerfile
  doozer/doozerlib/olm/bundle.py
Labels: approved, lgtm

#23 Add pip_system_certs to requirements
  doozer/requirements.txt
  elliott/pyproject.toml
Labels: approved, lgtm
