Repository openshift-eng/art-tools, pull requests merged in 2023-10, with the labels that each got.

#87 Log bug key when no component is set
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#89 Pin PyGithub
  doozer/requirements.txt
Labels: approved, lgtm

#88 Move cincinnati PR creation to promote.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, do-not-merge/hold

#80 Fix CVE mapping for RHCOS
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/tests/test_attach_cve_flaws_cli.py
Labels: approved, lgtm

#57 [ART-7781] --gather-dependencies for elliott verify-attached-operators
  elliott/elliottlib/cli/common.py
  elliott/elliottlib/cli/move_builds_cli.py
  elliott/elliottlib/cli/verify_attached_operators_cli.py
  elliott/tests/test_verify_attached_operators.py
Labels: approved, lgtm

#84 [gen-assembly] Allow limiting arches for all assembly types
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#90 Add support for Redis lists in pyartcd
  pyartcd/pyartcd/redis.py
Labels: approved, lgtm

#85 gen-assembly rhcos helper
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/gen_assembly_helper.py
Labels: approved, lgtm

#91 Add missing arg to format string
  pyartcd/pyartcd/locks.py
Labels: approved, lgtm

#97 Use component name consistent for reconciliation
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#94 Announce mass rebuild in slack
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#92 ART-3507 Refactor ocp4-scan
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/runtime.py
  doozer/tests/cli/test_scan_sources.py
Labels: approved, lgtm

#101 Notify about mass rebuilds when they actually start/complete
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#102 key source is not required
  doozer/doozerlib/source_modifications.py
Labels: approved, lgtm

#95 Exclude certain keys from config digest calculation
  doozer/doozerlib/image.py
Labels: approved, lgtm

#104 Tweak mass rebuild lock message
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#105 Revert "Exclude certain keys from config digest calculation"
  doozer/doozerlib/image.py
Labels: approved, lgtm

#106 Update microshift sync error message
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#109 Fix upstream_image_mirror
  doozer/doozerlib/cli/images_streams.py
Labels: lgtm

#110 [ART-7954] Ignore image config change on noop commit message
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#114 [verify-attached-operators] gather-dependencies Don't fail on move state error
  elliott/elliottlib/cli/common.py
  elliott/elliottlib/cli/verify_attached_operators_cli.py
Labels: approved, lgtm

#117 ART-7954 scan-sources:noop - Fetch commit for the metadata file
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#118 [build_microshift] Increase timeout to change to advisory to QE
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#99 Fix package version prints
  .github/workflows/doozer-unit-tests.yaml
  .github/workflows/elliott-unit-tests.yaml
  .github/workflows/pyartcd-unit-tests.yaml
  doozer/doozerlib/__init__.py
  doozer/doozerlib/cli/__init__.py
  doozer/setup.py
  elliott/elliottlib/__init__.py
  elliott/elliottlib/cli/common.py
  elliott/pyproject.toml
  pyartcd/pyartcd/__init__.py
  pyartcd/pyartcd/cli.py
  pyartcd/setup.py
Labels: approved, lgtm

#111 Revert "Revert "Exclude certain keys from config digest calculation""
  doozer/doozerlib/image.py
Labels: approved, lgtm

#103 ART-3506 Rebase openshift-priv if needed
  doozer/doozerlib/cli/scan_sources.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: lgtm, do-not-merge/hold

#120 Mark skipped scans as SKIPPED
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#121 ocp4-scan: signal skipped builds (for any reason)
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#122 ocp4-scan: add missing -rebase-priv option
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#127 ocp4-scan: distinguish among frozen and locked builds
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#123 Display removed locks in build title
  pyartcd/pyartcd/pipelines/cleanup_locks.py
Labels: lgtm

#128 [elliott go] Be exact when looking for golang builder image
  elliott/elliottlib/util.py
Labels: approved, lgtm

#129 Increase rebase log verbosity
  doozer/doozerlib/cli/scan_sources.py
Labels: approved

#131 Do not crash if config_digest is not found, just skip the check
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#126 Delete locks if associated build cannot be found
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/cleanup_locks.py
Labels: lgtm

#132 Only rebase into -priv one (if any) random component for each ocp4-scan
  doozer/doozerlib/cli/scan_sources.py
Labels: lgtm

#137 When nothing changed in ocp4-scan, track this in the build title
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#138 Do not break the build if API limit is reached
  doozer/doozerlib/cli/scan_sources.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#133 [find-builds] Log advisories that filtered builds are attached to
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/tests/test_find_builds_cli.py
Labels: approved, lgtm

#134 [build-microshift] Skip advisory prep if there is no advisory
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#139 Do not error out on multiple golang builders
  elliott/elliottlib/errata_async.py
Labels: lgtm

#140 [build-microshift] Verify only microshift advisory
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: lgtm

#142 ART-8041 Use git ls-remote instead of GitHub API
  doozer/doozerlib/cli/scan_sources.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#145 images-health: Run on Monday for weekdays frozen releases
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#136 Only output changed elements to keep output concise
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#147 Treat go-install just as go-build
  doozer/doozerlib/golang_builder_FIPS_wrapper.sh
Labels: approved, lgtm
