Repository openshift-eng/art-tools, pull requests merged in 2023-09, with the labels that each got.

#28 Migrate missing commits from aos-cd-jobs
  pyartcd/pyartcd/plashets.py
Labels: approved, lgtm

#29 Add .gitignore
  .gitignore
Labels: approved, lgtm

#25 [ART-7056] deprecate placeholder bug
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/cli/create_placeholder_cli.py
  elliott/elliottlib/cli/create_textonly_cli.py
  elliott/elliottlib/cli/repair_bugs_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/functional_tests/test_verify_attached_bugs.py
  elliott/tests/test_bzutil.py
  elliott/tests/test_repair_bugs_cli.py
Labels: approved, lgtm

#35 Migrate commits from aos-cd-jobs
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/advisory_drop.py
  pyartcd/pyartcd/pipelines/cleanup_locks.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/pyartcd/redis.py
  pyartcd/tests/pipelines/test_ocp4.py
  pyartcd/tests/test_locks.py
Labels: approved, lgtm

#32 gen-payload: respect exempted_packages option
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm

#33 Train Doozer to auto-create missing distgit branches
  doozer/doozerlib/distgit.py
  doozer/doozerlib/exectools.py
  doozer/doozerlib/metadata.py
  doozer/tests/test_distgit/test_generic_distgit.py
Labels: approved, lgtm

#30 Include rhcos build_id & image nvr in assembly issue
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#36 kick off scan after microshift build
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#34 gen-assembly: Stop creating microshift placeholder advisory for 4.12
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/tests/cli/test_gen_assembly.py
Labels: approved

#37 [ocp4_scan] Wait for redis lock manager connection destroy op
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#40 Revert "kick off scan after microshift build"
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#43 promote: Increase timeout to 24 hours
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#42 [ocp4] Handle rpm build failures
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/record.py
Labels: approved, lgtm

#44 distgit: Push to origin
  doozer/doozerlib/distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
Labels: approved, lgtm

#41 [promote] Make sure image advisory exists for candidate-type assemblies
  pyartcd/pyartcd/pipelines/promote.py
Labels: lgtm

#45 add dev container files
  .devcontainer/Containerfile
  .devcontainer/README.md
  .devcontainer/brewkoji.conf
  .devcontainer/doozer.settings.yaml
  .devcontainer/elliott.settings.yaml
  .devcontainer/krb5-redhat.conf
Labels: approved, lgtm

#46 Include a note for kernel[-rt] CVEs
  elliott/elliottlib/cli/find_bugs_kernel_cli.py
  elliott/tests/test_find_bugs_kernel_cli.py
Labels: approved, lgtm

#49 Handle EOL release phase
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/plashets.py
  pyartcd/pyartcd/util.py
  pyartcd/tests/test_util.py
Labels: approved, lgtm

#24 ART-7629 early kernel: only tag when kernel and kernel-rt are of same version
  doozer/doozerlib/cli/config_tag_rpms.py
  doozer/tests/cli/test_config_tag_rpms.py
Labels: approved

#31 [build-microshift] - Don't skip advisory prep and other job enhancements
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/util.py
  pyartcd/tests/test_util.py
Labels: approved, lgtm

#50 Skip check-bugs for releases not in 'release' phase
  pyartcd/pyartcd/pipelines/check_bugs.py
Labels: approved, lgtm

#54 Log nightly differences with WARNING level
  doozer/doozerlib/cli/get_nightlies.py
Labels: approved, lgtm

#48 mass-rebuilds: only for `streams.<stream>.image` attribute
  doozer/doozerlib/image.py
Labels: approved, lgtm

#52 ART-7624 Send qe email during promote rather than prepare
  pyartcd/config.example.toml
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/util.py
  pyartcd/tests/test_util.py
Labels: approved, lgtm

#53 Don't skip advisory prep if builds are pinned
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: lgtm

#58 Improve wording alignment PRs
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#38 ART-7628 Store Jenkins build path as lock identifier
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/cleanup_locks.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
  pyartcd/pyartcd/pipelines/review_cvp.py
  pyartcd/pyartcd/runtime.py
  pyartcd/pyartcd/slack.py
  pyartcd/tests/test_jenkins.py
Labels: approved, lgtm

#55 [promote] Move/verify advisories only for standard assemblies
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#59 ART-7628 cleanup locks follow up
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/cleanup_locks.py
Labels: approved, lgtm

#60 ART-7628 Store Jenkins build path as lock value
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/olm_bundle.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/rebuild.py
Labels: approved, lgtm

#61 Use : separator for lock names
  pyartcd/pyartcd/locks.py
  pyartcd/tests/test_locks.py
Labels: approved, lgtm

#62 Use : separator for fail counters in Redis
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#63 Only keep fail counters > 0
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/redis.py
Labels: lgtm

#64 Log cgit url error
  doozer/doozerlib/metadata.py
Labels: approved, lgtm

#70 gen-assembly: Generate MISSING_SHIP_OK_TAG for kernels without ship-ok
  doozer/doozerlib/assembly_inspector.py
Labels: approved, lgtm

#72 find-builds: Fix for include-shipped
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#73 Make jenkins test environment independent
  pyartcd/tests/test_jenkins.py
Labels: approved, lgtm

#71 attach-cve-flaws: Permit explicitly included bugs
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#69 gen-payload: Require explicit permits for non-stream assemblies
  doozer/doozerlib/cli/release_gen_payload.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#75 minor tweaks
  .devcontainer/Containerfile
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/runtime.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/runtime.py
Labels: approved, lgtm

#76 ART-7806 check images health for stream assembly only
  doozer/doozerlib/cli/config_tag_rpms.py
  doozer/doozerlib/cli/images_health.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/rpm_builder.py
Labels: approved, lgtm

#74 Wrap try/lock/except/finally operations in locks.run_with_lock()
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/olm_bundle.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/tests/pipelines/test_ocp4.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#77 Make compose lock assembly aware
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/tests/test_locks.py
Labels: approved, lgtm

#78 Skip fail counter update for build-sync dry runs
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#79 Fix TypeError in verify-attached-bugs
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm

#81 Convert all image labels to string
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#51 [ART-7730] Trigger SAST scans for builds in candidate tags
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/scan_osh.py
  doozer/doozerlib/runtime.py
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/brew_scan_osh.py
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#82 ART-7853 Optional images no longer apply
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/state.py
Labels: approved, lgtm
