Repository openshift-eng/art-tools, pull requests merged in 2023-12, with the labels that each got.

#219 [ART-7926] [scan-osh] Enable OCPBUGS pipeline for ART managed RPMs
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#223 Skip emails during promotion for ECs
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#224 [scan-osh] Skip if NVRs are same, minor fixes
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#226 Increase verbosity in doozer images:streams prs list logs
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#227 ART-8427: get rhcos version from release
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, jira/valid-reference

#229 images:print add --show-disabled flag
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#228 [scan-osh] include base, non-release images, skip bundle builds
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#231 use --load-disabled
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#232 Refactor doozer olm-bundle to olm_bundle.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/olm_bundle.py
Labels: approved, lgtm

#234 [scan-osh] skip comment if skip_diff_check is enabled
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#236 [scan-osh] trigger only for scheduled job
  doozer/doozerlib/cli/scan_osh.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: approved, lgtm

#205 update operator-sdk job update subtask function
  pyartcd/pyartcd/jira.py
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
Labels: lgtm

#237 scan-sources pattern match for exempted packages
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/repodata.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/test_metadata.py
Labels: approved

#241 Refactor doozer config:* commands to separate file
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/config.py
Labels: approved, lgtm

#244 Skip outdated buildconfigs when triggering builds
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#239 ART-8191 Deprecate unused code paths in create advisory
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/add_metadata_cli.py
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/cli/create_placeholder_cli.py
  elliott/elliottlib/constants.py
  elliott/elliottlib/errata.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: lgtm

#246 ART-8476 doozer images:rebase assert RHEL version equivalence in Dockerfiles
  doozer/doozerlib/distgit.py
Labels: approved, do-not-merge/hold

#256 ART-8483 canonical builders override
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#259 elliott - Deprecate unused commands and get release from synopsis
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/advisory_impetus_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/list_cli.py
  elliott/elliottlib/cli/puddle_advisories_cli.py
  elliott/elliottlib/cli/rpmdiff_cli.py
  elliott/elliottlib/errata.py
  elliott/elliottlib/util.py
  elliott/functional_tests/test_create.py
  elliott/tests/test_errata.py
  elliott/tests/test_find_builds_cli.py
Labels: approved, lgtm

#261 Deprecate errata xmlrpc calls; instead use http api
  doozer/doozerlib/cli/config_plashet.py
  elliott/elliottlib/constants.py
  elliott/elliottlib/errata.py
  elliott/tests/test_errata.py
Labels: approved, do-not-merge/hold

#260 ART-8476 handle when clause
  doozer/doozerlib/distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
Labels: approved, lgtm

#265 Fix altconfig getter
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#266 ART-8481: add release version in alignment pr
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#268 Protect build-sync for stream assembly with a Lock
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#243 [ART-8256] Add Art-Dash Link to Health:Images Reports
  doozer/doozerlib/cli/images_health.py
  doozer/tests/test_images_health.py
Labels: approved, lgtm

#245 [ART-8416] Add support for checking external packages
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm

#248 Refactor doozer images:* commands
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/images.py
Labels: approved, lgtm

#262 Say build-sync is good again
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#258 [prs list] Look for PRs by openshift-bot by default
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#267 Track Jenkins job run on alignment PRs
  doozer/doozerlib/cli/images_streams.py
Labels: lgtm

#270 Fix fail count comparison
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#271 Fix sync-ci-images
  doozer/doozerlib/util.py
Labels: approved, lgtm

#269 Scan-osh: Don't error out early
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#274 added owner
  OWNERS
Labels: approved, lgtm

#272 ART-8481: new alignment prs check method
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#275 ART-7803: Edit go.mod with ci build root
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#277 go.mod editing: Look at git staging area for go/no-go
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#249 ART-8426 Support showing go version for payload
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/get_golang_versions_cli.py
  elliott/elliottlib/util.py
  elliott/tests/test_get_golang_versions_cli.py
Labels: approved, lgtm

#278 Move duplicated functions to artcommon
  artcommon/artcommonlib/arch_util.py
  artcommon/tests/test_arch_util.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/gen_assembly_helper.py
  doozer/doozerlib/cli/get_nightlies.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/image.py
  doozer/doozerlib/rhcos.py
  doozer/doozerlib/util.py
  doozer/tests/test_util.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/find_unconsumed_rpms.py
  elliott/elliottlib/cli/rhcos_cli.py
  elliott/elliottlib/cvp.py
  elliott/elliottlib/rhcos.py
  elliott/elliottlib/util.py
  elliott/tests/test_find_builds_cli.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/util.py
Labels: lgtm

#279 Fix elliott go command
  elliott/elliottlib/cli/get_golang_versions_cli.py
  elliott/tests/test_get_golang_versions_cli.py
Labels: lgtm

#280 Move assertion module to artcommon
  artcommon/artcommonlib/assertion.py
  artcommon/tests/test_assertion.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/exectools.py
  doozer/doozerlib/runtime.py
  doozer/tests/test_exectools.py
  elliott/elliottlib/assertion.py
  elliott/elliottlib/exectools.py
  elliott/elliottlib/imagecfg.py
  elliott/tests/test_assertion.py
Labels: approved, lgtm

#221 ART-8114 gen-assembly configures prerelease advisories
  doozer/doozerlib/cli/release_gen_assembly.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#263 ART-8115 Modify prepare-release job for prereleases
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/elliottlib/errata.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm
