Repository openshift-eng/art-tools, pull requests merged in 2024-06, with the labels that each got.

#665 [ART-9794] Notify on image rebase failures, do not crash ocp4
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#666 Update docs + pygit2
  README.md
  doozer/requirements-dev.txt
  elliott/pyproject.toml
  ocp-build-data-validator/requirements.txt
  pyartcd/requirements.txt
Labels: approved, lgtm

#648 [Snyk] Security upgrade requests from 2.31.0 to 2.32.0
  elliott/y-stream/requirements.txt
Labels: approved

#646 [Snyk] Security upgrade requests from 2.31.0 to 2.32.0
  pyartcd/requirements.txt
Labels: approved

#670 Alert about rebase failures only for stream assembly
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#662 ART-9793 Handle the new 'signing' phase
  artcommon/artcommonlib/release_util.py
  artcommon/tests/test_util.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/check_bugs.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#654 Do not set art-attention icon on FIPS failure messages
  pyartcd/pyartcd/pipelines/scan_fips.py
Labels: approved, lgtm

#677 Seek for 'org.opencontainers.image.version' label in RHCOS first
  doozer/doozerlib/cli/scan_sources.py
  doozer/tests/cli/test_scan_sources.py
Labels: approved, lgtm

#678 Get RHCOS build id in old case correctly
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#668 Lint fix
  elliott/elliottlib/cli/find_builds_cli.py
  tox.ini
Labels: approved, lgtm

#594 Regression alerts only if next version is GA
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/runtime.py
  elliott/tests/test_verify_attached_bugs_cli.py
  pyartcd/pyartcd/pipelines/check_bugs.py
Labels: approved, lgtm, tide/merge-method-squash

#686 Ignore okd config changes for triggering production builds
  doozer/doozerlib/image.py
Labels: approved, lgtm

#688 Revert "Ignore okd config changes for triggering production builds"
  doozer/doozerlib/image.py
Labels: approved, lgtm

#689 Sigstore sign release payloads prior to adding to the release controller
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#690 Set prerelease label in bundle build always
  doozer/doozerlib/olm/bundle.py
Labels: lgtm

#691 Check prerelease label explicitly
  doozer/doozerlib/olm/bundle.py
Labels: lgtm

#695 promote: Fix invalid json
  pyartcd/pyartcd/s3.py
Labels: approved, lgtm

#701 Pin tenacity 8.3
  doozer/requirements.txt
  elliott/pyproject.toml
  pyartcd/requirements.txt
Labels: approved, lgtm

#700 ART-9934: Clean up FIPS installer archive paths
  pyartcd/pyartcd/oc.py
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, jira/valid-reference

#694 ART-8684 Automatically remove invalid builds
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/errata.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm, tide/merge-method-squash

#698 Tweak verify bugs for advance advisory
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/errata.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: lgtm

#702 verify-attached-bugs: Use raw advisory fetch to be fast and less error prone
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/errata.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm

#672 ART-6673 notify QE release ready through update QE release repo
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, tide/merge-method-squash

#697 prepare-release: Explicitly add newly created advisory to batch
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/errata_async.py
  elliott/tests/test_errata_async.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#692 prepare-release: Reuse existing batch ID
  elliott/elliottlib/errata_async.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved

#706 set --import-mode=PreserveOriginal for tagging
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#709 Fix prepare release
  elliott/elliottlib/cli/create_cli.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: lgtm

#710 fix --import-mode=PreserveOriginal command
  pyartcd/pyartcd/pipelines/promote.py
Labels: lgtm

#714 Fix newly created advisory ID being set to 0
  elliott/elliottlib/cli/create_cli.py
Labels: lgtm

#712 fix yaml load function
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, tide/merge-method-squash

#669 ART-9021 get rid of auto in canonical_builders_from_upstream
  artcommon/artcommonlib/build_util.py
  doozer/doozerlib/release_schedule.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  ocp-build-data-validator/validator/json_schemas/assembly_group_config.schema.json
  ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json
Labels: approved, lgtm, tide/merge-method-squash

#716 ART-9844: Stop editing go.mod
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#717 ART-9503 Handle multiple plashet host locations
  pyartcd/pyartcd/constants.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/pyartcd/plashets.py
  pyartcd/tests/pipelines/test_rebuild.py
Labels: approved, lgtm

#719 [sast] refactor to use --config=auto
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm, tide/merge-method-squash

#696 Fix release bumps for non ART RPMs
  pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
  pyartcd/tests/test_rebuild_golang_rpms.py
Labels: approved, lgtm

#720 Revert "ART-9503 Handle multiple plashet host locations"
  pyartcd/pyartcd/constants.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/pyartcd/plashets.py
  pyartcd/tests/pipelines/test_rebuild.py
Labels: approved, lgtm

#724 get art-attention for build-microshift error with releases
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: lgtm, tide/merge-method-squash

#726 ART-9555 deprecate kernel ship-ok tag check for assembly
  doozer/doozerlib/assembly_inspector.py
  doozer/tests/test_assembly_inspector.py
Labels: approved, lgtm, tide/merge-method-squash

#713 ART-9937: Publish openshift-install-fips for multiarch payloads
  pyartcd/pyartcd/oc.py
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, jira/valid-reference

#730 ART-9555 update alert message for untag event
  pyartcd/pyartcd/pipelines/tag_rpms.py
Labels: approved, lgtm, tide/merge-method-squash

#725 Improve log handling
  artcommon/artcommonlib/logutil.py
  doozer/doozerlib/runtime.py
  doozer/tests/test_runtime.py
  elliott/elliottlib/runtime.py
Labels: approved, lgtm

#731 operator-sdk-sync: Accommodate for rhel9 image name change
  pyartcd/pyartcd/constants.py
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
Labels: approved, lgtm

#732 Also sigstore sign release images
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/sigstore_sign.py
Labels: approved, lgtm

#729 Revert "Revert "ART-9503 Handle multiple plashet host locations""
  pyartcd/pyartcd/constants.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/pyartcd/plashets.py
  pyartcd/tests/pipelines/test_rebuild.py
Labels: approved
