Repository openshift-eng/art-tools, pull requests merged in 2024-08, with the labels that each got.

#813 Move gitdata to art-common
  artcommon/artcommonlib/constants.py
  artcommon/artcommonlib/gitdata.py
  doozer/doozerlib/cli/config.py
  doozer/doozerlib/constants.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/source_resolver.py
  doozer/tests/cli/test_rpms_build.py
  doozer/tests/test_osbs2.py
  doozer/tests/test_rpm_builder.py
  elliott/elliottlib/gitdata.py
  elliott/elliottlib/runtime.py
Labels: approved, lgtm

#822 find-bugs:golang: Allow filtering by multiple cve ids
  elliott/elliottlib/cli/find_bugs_golang_cli.py
Labels: lgtm

#829 ocp-build-data-validator: Print json path with message
  ocp-build-data-validator/validator/schema/image_schema.py
  ocp-build-data-validator/validator/schema/releases_schema.py
Labels: approved, lgtm

#833 [Snyk] Security upgrade aiohttp from 3.8.6 to 3.10.2
  pyartcd/requirements.txt
Labels: approved, lgtm

#836 Remove blocked_by_bz references
  elliott/elliottlib/bzutil.py
  elliott/tests/test_bzutil.py
Labels: approved, lgtm

#818 [ART-10250] Reuse advisories and jira for assembly
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: approved, lgtm

#827 for nightlies, set --import-mode=PreserveOriginal
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#837 Use PreserveOriginal when re-triggering latest nightly
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#838 Add importPolicy PreserveOriginal for image tags
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm, tide/merge-method-squash

#839 Allow OKD-only images and references to quay.io images
  doozer/doozerlib/cli/images_okd.py
Labels: approved, lgtm

#840 Exclude delivery from digest calculation
  doozer/doozerlib/image.py
Labels: approved, lgtm

#841 Add delivery to validator image config schema
  ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json
Labels: approved, lgtm

#842 [ART-10376] Fix latest builds retrieval in FIPS scan
  doozer/doozerlib/cli/scan_fips.py
Labels: approved, lgtm

#844 Retry oc commands to rule out flakes
  pyartcd/pyartcd/oc.py
Labels: approved, lgtm

#847 Retry on gss API login failure
  doozer/doozerlib/brew.py
Labels: approved, lgtm

#855 [ART-10504] Move some OpenTelemetry helper functions to artcommonlib
  artcommon/artcommonlib/telemetry.py
  artcommon/requirements.txt
  artcommon/setup.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/telemetry.py
  pyartcd/pyartcd/exectools.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/telemetry.py
Labels: approved, lgtm

#854 [ART-10504] Remove k_ocp4 job and doozer k:images:rebase verb
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/k_distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/runtime.py
  doozer/tests/test_distgit/test_generic_distgit.py
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/pipelines/k_ocp4.py
Labels: approved, lgtm

#861 Fix RuntimeError: await wasn't used with future
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#857 [ART-10504] Update cmd_assert_async and cmd_assert_async in artcommonlib
  artcommon/artcommonlib/exectools.py
  artcommon/tests/test_exectools.py
  doozer/doozerlib/cli/get_nightlies.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_fips.py
  doozer/doozerlib/cli/scan_osh.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/rpm_builder.py
  doozer/tests/test_distgit/test_rpm_distgit.py
  doozer/tests/test_rpm_builder.py
  pyartcd/pyartcd/git.py
  pyartcd/pyartcd/oc.py
  pyartcd/pyartcd/pipelines/advisory_drop.py
  pyartcd/pyartcd/pipelines/brew_scan_osh.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/check_bugs.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
  pyartcd/pyartcd/pipelines/images_health.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/olm_bundle.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
  pyartcd/pyartcd/pipelines/review_cvp.py
  pyartcd/pyartcd/pipelines/scan_fips.py
  pyartcd/pyartcd/pipelines/scan_for_kernel_bugs.py
  pyartcd/pyartcd/pipelines/sigstore_sign.py
  pyartcd/pyartcd/pipelines/tag_rpms.py
  pyartcd/pyartcd/pipelines/tarball_sources.py
  pyartcd/pyartcd/pipelines/update_golang.py
  pyartcd/pyartcd/plashets.py
  pyartcd/pyartcd/s3.py
  pyartcd/pyartcd/signatory.py
  pyartcd/pyartcd/util.py
  pyartcd/tests/pipelines/test_gen_assembly.py
  pyartcd/tests/pipelines/test_ocp4.py
  pyartcd/tests/pipelines/test_rebuild.py
  pyartcd/tests/pipelines/test_tarball_sources.py
  pyartcd/tests/test_util.py
Labels: approved, lgtm

#856 [ART-10504] is_commit_in_public_upstream should respect source_dir
  doozer/doozerlib/util.py
Labels: approved, lgtm

#858 [ART-10504] Add helper function SourceResolver.get_source_dir
  doozer/doozerlib/distgit.py
  doozer/doozerlib/source_resolver.py
  doozer/tests/test_distgit/test_generic_distgit.py
  doozer/tests/test_source_resolver.py
Labels: approved, lgtm

#853 [ART-10504] Doozer: Move some fields from ImageDistGitRepo to ImageMetadata
  artcommon/artcommonlib/build_util.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/tests/test_distgit/support.py
  doozer/tests/test_distgit/test_generic_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_push_image.py
  doozer/tests/test_distgit/test_resolve_image_from_upstream_parent.py
  doozer/tests/test_metadata.py
Labels: approved, lgtm

#863 Set the RHCOS build timeout to 6 hours
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, lgtm

#862 #aos-art has been renamed into #forum-ocp-art
  pyartcd/pyartcd/pipelines/images_health.py
Labels: lgtm

#864 Add lgarciaaco to owners
  OWNERS
Labels: lgtm

#867 Add retries to build-sync pipeline
  artcommon/artcommonlib/exectools.py
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#843 Enable promote with upgrades_next edges
  ocp-build-data-validator/validator/json_schemas/assembly_group_config.schema.json
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, do-not-merge/hold, tide/merge-method-squash

#869 Add retry to jira fields fetch
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#872 Doozer: Remove functional_tests
  doozer/functional_tests/README.md
  doozer/functional_tests/__init__.py
  doozer/functional_tests/test_cleanup.py
  doozer/functional_tests/test_config.py
  doozer/functional_tests/test_images.py
  doozer/functional_tests/test_release.py
  doozer/functional_tests/test_rpms.py
  doozer/setup.py
Labels: approved, lgtm

#812 [ART-9920] add new cve type field
  elliott/elliottlib/bzutil.py
  elliott/tests/test_bzutil.py
Labels: lgtm, tide/merge-method-squash

#877 images-health: retry on DB connection error
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#878 Retry when fetching builds from Errata
  elliott/elliottlib/errata.py
Labels: approved, lgtm

#879 ART-10297 art-cd: bump Python to 3.11
  art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
Labels: approved, lgtm

#880 Add a retry to Elliott get brew build
  elliott/elliottlib/errata.py
Labels: approved, lgtm

#881 replace deprecated function
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, lgtm

#882 Retry on manifest-tool errors
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#886 find-builds: Do not filter out shipped builds if pinned
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#887 Retry when pushing bundles to distgit
  doozer/doozerlib/olm/bundle.py
Labels: approved, lgtm

#888 olm_bundle: Serialize rhpkg ops and respect canonical builder config
  doozer/doozerlib/cli/olm_bundle.py
Labels: approved, lgtm

#889 ocp4: never scan for changes, always build what's pinned
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: approved, lgtm

#883 ART-10562 Run scheduled ocp4-scan in pyartcd
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/scheduled/__init__.py
  pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan.py
Labels: approved, lgtm

#890 Define lock policy for SCAN
  pyartcd/pyartcd/locks.py
Labels: approved, lgtm

#891 scheduled-ocp4-scan: do not block until building
  pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan.py
Labels: approved, lgtm

#892 Format olm-bundle locks correctly
  pyartcd/pyartcd/locks.py
Labels: approved, lgtm

#896 ocp4-scan mark what's changed in the description
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#894 Restore ocp4_scan backlinks
  pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan.py
Labels: approved, lgtm

#897 ocp4-scan: log when no changes are detected
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#895 Refactor scheduled ocp4-scan
  pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan.py
Labels: approved
