Repository openshift-eng/art-tools, pull requests merged in 2024-09, with the labels that each got.

#885 ART-10297 Move python3.8 references to 3.11
  .devcontainer/Containerfile
  .github/workflows/unit-tests.yaml
  Makefile
  doozer/.devcontainer/dev.Dockerfile
  doozer/Makefile
  doozer/tox.ini
  elliott/.devcontainer/dev.Dockerfile
  elliott/Makefile
  elliott/tox.ini
  ocp-build-data-validator/deploy/Dockerfile.base
  ocp-build-data-validator/tox.ini
  pyartcd/Makefile
  pyartcd/tox.ini
Labels: approved, tide/merge-method-squash

#802 [operator and bundle builds] Complain if image references not found
  doozer/doozerlib/distgit.py
  doozer/doozerlib/olm/bundle.py
Labels: approved, do-not-merge/hold, tide/merge-method-squash

#901 Prevent endless appending of --recurse-submodules to gitargs
  artcommon/artcommonlib/git_helper.py
Labels: approved, lgtm

#903 git_clone() remove side effects
  artcommon/artcommonlib/git_helper.py
Labels: approved, lgtm

#906 log PR link after successful comment
  doozer/doozerlib/comment_on_pr.py
Labels: approved, lgtm

#908 Retry `oc image info` for gen-assembly
  doozer/doozerlib/cli/get_nightlies.py
Labels: approved, lgtm

#909 Increase RHCOS timeout to 8 hours
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, lgtm

#527 [ART-9330] [ART-8971] new embargo process
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm, tide/merge-method-squash

#820 [ART-10504] Doozer: Add command for rebasing images with Konflux
  artcommon/artcommonlib/git_helper.py
  artcommon/tests/test_git_helper.py
  doozer/doozerlib/backend/build_repo.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/constants.py
  doozer/doozerlib/runtime.py
  doozer/tests/backend/__init__.py
  doozer/tests/backend/test_build_repo.py
Labels: lgtm

#912 log jenkins build url in reconciliation ticket
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#915 Konflux rebase: Add --repo-type parameter
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/cli/images_konflux.py
Labels: approved, lgtm

#859 WIP: Add Doozer verb to build images with Konflux
  doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/constants.py
  doozer/requirements.txt
Labels: do-not-merge/work-in-progress, lgtm

#919 Add importlib-resources to doozer requirements
  doozer/requirements.txt
Labels: approved, lgtm

#920 pyartcd: Initialize logging on start
  artcommon/artcommonlib/logutil.py
  pyartcd/pyartcd/cli.py
Labels: approved, lgtm

#921 images:rebase - Fix modifications script path
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#918 ART-10668 Replace pip with uv
  .github/workflows/unit-tests.yaml
  Makefile
  install.sh
  tox.ini
Labels: approved, lgtm

#923 fix aligment bug search
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#924 add option to skip get_nightlies
  pyartcd/pyartcd/pipelines/gen_assembly.py
  pyartcd/pyartcd/slack.py
  pyartcd/tests/pipelines/test_gen_assembly.py
Labels: approved, lgtm, tide/merge-method-squash

#905 ART-10624: added new fields for automatically created JIRAS
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#911 ART-9803 Add Konflux db integration
  artcommon/artcommonlib/konflux/__init__.py
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/runtime.py
  artcommon/requirements.txt
  artcommon/tests/test_konflux_build_record.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/runtime.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/find_konflux_builds_cli.py
  elliott/elliottlib/runtime.py
Labels: approved, lgtm

#928 Correct destination tags when replacing priv build
  doozer/doozerlib/cli/release_gen_payload.py
Labels: lgtm

#925 gen-assembly read from private nightlies
  doozer/doozerlib/cli/get_nightlies.py
  doozer/doozerlib/constants.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm, tide/merge-method-squash

#934 Promote pullspec fix
  pyartcd/pyartcd/pipelines/promote.py
Labels: lgtm

#932 Skip bug filtering when no bugs
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/tests/test_find_bugs_sweep_cli.py
Labels: tide/merge-method-squash

#938 Stop publishing to old plashet host
  pyartcd/pyartcd/constants.py
Labels: approved, lgtm

#942 Reconciliation jiras: Only for 4.16+
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#943 konflux builder: Wait for status attribute to appear
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#946 update flaw bug search requirement
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#947 Doozer: Disallow extra 'v' in version string
  doozer/doozerlib/cli/__init__.py
Labels: approved, lgtm

#951 Retry konflux builds
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm, tide/merge-method-squash

#952 konflux retry fix
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#953 Raise only when build failed in all retries
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#954 Skip build-microshift if microshift advisory not found
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#944 ART-10831 Store successful RPM Brew builds in BigQuery
  doozer/doozerlib/cli/rpms.py
Labels: approved, lgtm

#948 ART-10831 Store failed Brew image builds in BigQuery
  artcommon/artcommonlib/git_helper.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_git_helper.py
  doozer/doozerlib/backend/build_repo.py
  doozer/doozerlib/distgit.py
  doozer/tests/backend/test_build_repo.py
Labels: approved, lgtm

#959 Revert "ART-10624: added new fields for automatically created JIRAS"
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#958 Report trackers that link to vulnerability-draft bug
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#941 Define konflux_db.get_latest_builds()
  artcommon/artcommonlib/bigquery.py
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/runtime.py
  artcommon/requirements.txt
  artcommon/tests/test_big_query.py
  artcommon/tests/test_konflux_db.py
  elliott/elliottlib/cli/find_konflux_builds_cli.py
Labels: approved, lgtm

#961 ART-10624: added new fields for automatically created JIRAS
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#962 Move GCP project, dataset and table ID to art-tools constants
  artcommon/artcommonlib/bigquery.py
  artcommon/artcommonlib/constants.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/runtime.py
  artcommon/tests/test_big_query.py
  artcommon/tests/test_konflux_db.py
Labels: approved, lgtm

#963 Move redis port and hostname to art-tools
  artcommon/artcommonlib/constants.py
  artcommon/artcommonlib/redis.py
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#852 ART-10516 Fetch and validate fixed in versions from go vulnerability DB
  elliott/elliottlib/cli/find_bugs_golang_cli.py
Labels: lgtm, do-not-merge/hold, tide/merge-method-squash

#966 deprecate pyartcd/pyartcd/pipelines/report_rhcos.py
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/pipelines/report_rhcos.py
Labels: approved, lgtm

#967 deprecate upload_image
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm

#968 Use the distgit key as primary image name when storing Konflux builds
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#969 Only print a warning when DBs cannot be initialized
  artcommon/artcommonlib/runtime.py
  doozer/doozerlib/runtime.py
Labels: approved, lgtm

#965 [ART-10716] update slack upload function
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm

#971 Allow multiple signing keys and rekor tlog for cosign
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/sigstore_sign.py
  pyartcd/pyartcd/signatory.py
Labels: lgtm

#977 fix cosign error
  pyartcd/pyartcd/signatory.py
Labels: approved, lgtm

#970 [ART-10834] images-health: fetch build info from Konflux DB
  artcommon/artcommonlib/bigquery.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
  doozer/doozerlib/cli/images_health.py
  doozer/tests/test_images_health.py
  pyartcd/pyartcd/pipelines/images_health.py
Labels: approved, lgtm

#975 Add sticky revert functionality to gen-payload
  doozer/doozerlib/cli/release_gen_payload.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: lgtm

#978 [Konflux] Fix resolving short images in streams.yml
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#983 Log more when there is an invalid flaw bug
  elliott/elliottlib/bzutil.py
  elliott/tests/test_bzutil.py
Labels: tide/merge-method-squash

#982 [konflux] replace golang stream with brew.registry
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#980 Fix sticky revert when annotation is not present
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#984 elliott: Filter out archived target versions
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#985 Revert "Fix sticky revert when annotation is not present"
  doozer/doozerlib/cli/release_gen_payload.py
Labels: lgtm, do-not-merge/hold

#986 Improve comments for revert-from logic
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#987 verify-bugs: Check for invalid bug status first
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm

#989 konflux build: Fix a deadlock when waiting for failed parents
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#988 ocp4_konflux: Add --skip-rebase option
  doozer/doozerlib/backend/konflux_image_builder.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: lgtm

#991 Promote arches in sequence
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, tide/merge-method-squash
