Repository openshift-eng/art-tools, pull requests merged in 2024-11, with the labels that each got.

#1103 ART-10995 fix false alarm for regression check
  artcommon/artcommonlib/util.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm

#1106 fix gh workflow
  .github/workflows/unit-tests.yaml
Labels: approved, lgtm, tide/merge-method-squash

#1107 [konflux] increase sbom-syft-generate task memory
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1099 Optimize checks when scanning images
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1108 Don't close 'customer portal' subtask automatically
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
Labels: approved, lgtm

#1109 pass doozer data path for get_signing_mode
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#1110 ART-10882: Get RHCOS to build on new host
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, lgtm, jira/valid-reference

#1111 fix ga tasks url
  artcommon/artcommonlib/util.py
Labels: approved, lgtm

#1112 validator: add image_upstream_mirror to ci_alignment properties
  ocp-build-data-validator/validator/json_schemas/image_content.base.schema.json
Labels: approved, lgtm

#1113 find konflux builds: Do not constrain by end time in default search
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
Labels: approved, lgtm, tide/merge-method-squash

#1115 [konflux] skip-checks param
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/images_konflux.py
Labels: approved, lgtm

#940 ART-10832: do not use reference nightlies for promotion
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm, jira/valid-reference

#1054 ART-10563 Build bootc image as part of build-microshift-bootc job
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/plashet.py
  doozer/doozerlib/util.py
  elliott/elliottlib/runtime.py
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
  pyartcd/pyartcd/plashets.py
  pyartcd/pyartcd/util.py
Labels: approved, do-not-merge/hold, tide/merge-method-squash

#1120 ART-11251: [konflux] Build source image by default
  doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml
Labels: jira/valid-reference

#1121 ART-11251: [konflux] set summary, description labels for rebase
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm, jira/valid-reference

#1122 Schedule ocp4-scan-konflux
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
  pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
  pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan_konflux.py
Labels: approved, lgtm

#1124 ocp4-scan: ignore locks on dry-run mode
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
Labels: approved, lgtm

#1126 Build and push bootc to official ART repo
  doozer/doozerlib/constants.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
Labels: approved, lgtm

#1130 ART-11251: [konflux] set dummy default labels
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm, jira/valid-reference

#1131 Include microshift in plashet sync only for named assemblies
  doozer/doozerlib/cli/config_plashet.py
Labels: approved, lgtm

#1137 Re-write konflux_db.search_builds_by_fields() to handle extra patterns
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
Labels: approved, lgtm

#1141 Move isolate_timestamp_in_release() to artcommon
  artcommon/artcommonlib/release_util.py
  artcommon/tests/test_util.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/doozerlib/util.py
  doozer/tests/test_util.py
Labels: approved, lgtm

#1140 rhcos host: All versions to new host
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, lgtm

#1142 Remove duplicated functions from redis.py
  artcommon/artcommonlib/redis.py
Labels: approved, lgtm

#1143 Add an optional expire flag to new Redis keys
  artcommon/artcommonlib/redis.py
Labels: approved, lgtm

#1145 Logging cleanup
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/tests/test_attach_cve_flaws_cli.py
Labels: do-not-merge/work-in-progress, tide/merge-method-squash

#1148 Introduce build plan for konflux builds
  doozer/doozerlib/cli/images_konflux.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1150 Introduce regex matching in konflux_db.search_builds_by_fields()
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
Labels: approved, lgtm

#1153 Point images-health links to the new build history UI
  doozer/doozerlib/cli/images_health.py
  doozer/doozerlib/constants.py
  doozer/tests/cli/test_images_health.py
Labels: approved, lgtm

#1158 ART-11441: [konflux] Update URLs to point to new cluster
  doozer/doozerlib/constants.py
Labels: approved, lgtm, jira/valid-reference

#1157 Add default value for otel endpoint
  artcommon/artcommonlib/constants.py
  doozer/doozerlib/telemetry.py
  pyartcd/pyartcd/telemetry.py
Labels: lgtm

#1161 Fix batch creation
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#1160 [konflux] Build aarch64 regularly as well
  pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
Labels: approved, lgtm

#1163 Add force-image-build option to golang builder pipeline
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#1164 Start RHCOS arch jobs earlier
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, lgtm
