Repository openshift-eng/art-tools, pull requests merged in 2024-12, with the labels that each got.

#1165 ART-3797: add detail to build-sync fail notification in case of non-v…
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm, jira/valid-reference

#1167 [konflux] set build retires to 3
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1168 [konflux] Fail when SBOMs can't be accessed (update)
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: lgtm

#1171 Add allowed property to accommodate 5768
  ocp-build-data-validator/validator/json_schemas/image_content.base.schema.json
Labels: approved, lgtm

#1172 Add member to ci_alignment allowed keys
  ocp-build-data-validator/validator/json_schemas/image_content.base.schema.json
Labels: approved, lgtm

#1173 [konflux] add ignore locks function
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: lgtm

#1174 ART-11506: [konflux] update dockerignore to include oit dir
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1175 ART-11446: images-health should report failures only when fail count > 1
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm, jira/valid-reference

#1136 [ART-11187] add tag-builds parameter and support update go major version
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: tide/merge-method-squash

#1176 Exclude images not enabled in Konflux from the scan report
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1180 build-sync: when notifying failures, print the report in a slack thread
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1181 Konflux: Remove artifact_type from KonfluxRecord and KonfluxBundleBuild
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/tests/test_konflux_db.py
Labels: approved, lgtm

#1183 Konflux: Ignore ConflictError when creating a resource
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1182 allow go previous is none
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: lgtm

#1186 [konflux] support VM override
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1162 move yaml lib into artcommon lib
  artcommon/artcommonlib/util.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/review_cvp.py
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm, tide/merge-method-squash

#1185 Revert "[konflux] update apply-tags timeout"
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1190 load batch relase from config
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#1192 use global yaml
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#1191 Fix build-sync failure notifications
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1193 Get mirror behavior to art-tools
  art-cluster/cloudflare/.gitignore
  art-cluster/cloudflare/README.md
  art-cluster/cloudflare/package-lock.json
  art-cluster/cloudflare/package.json
  art-cluster/cloudflare/src/checkAccess.ts
  art-cluster/cloudflare/src/config.ts
  art-cluster/cloudflare/src/index.ts
  art-cluster/cloudflare/src/render.ts
  art-cluster/cloudflare/src/secretsManager.ts
  art-cluster/cloudflare/src/static.ts
  art-cluster/cloudflare/src/types.ts
  art-cluster/cloudflare/tsconfig.json
  art-cluster/cloudflare/wrangler.toml
  art-cluster/cloudfront/generate_range_array.py
  art-cluster/cloudfront/mirror/README.md
  art-cluster/cloudfront/mirror/cloudfront_function_cgw-redirector.js
  art-cluster/cloudfront/mirror/lambda_art-srv-enterprise-s3-get-index-html-gen.py
  art-cluster/cloudfront/mirror/lambda_art-srv-enterprise-s3-redirect-base-to-index-html.py
  art-cluster/cloudfront/mirror/lambda_art-srv-request-basic-auth.py
  art-cluster/cloudfront/mirror/lambda_r2_art-srv-enterprise-s3-get-index-html-gen.py
  art-cluster/cloudfront/mirror/lambda_r2_art-srv-request-basic-auth.py
  art-cluster/cloudfront/mirror/lambda_r2_lib.py
  art-cluster/cloudfront/rhcos.mirror/README.md
  art-cluster/cloudfront/rhcos.mirror/lambda_srv_rhcos_mirror.py
Labels: approved, lgtm

#1194 konflux: a cleanup
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm, do-not-merge/hold

#1096 Get source rpm from purl
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/requirements.txt
Labels: approved, tide/merge-method-squash

#1196 [konflux] set build source image as true
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml
Labels: approved, lgtm

#1199 Update the build title with version
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: lgtm

#1201 ocp4-konflux: print image build info in the job description
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1197 [konflux] pull template from art-konflux-template repo
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml
  doozer/doozerlib/constants.py
Labels: approved, lgtm

#1203 deprecate 2015 IT cert
  art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
  doozer/doozerlib/coverity.py
  ocp-build-data-validator/Dockerfile
  ocp-build-data-validator/deploy/Dockerfile.base
Labels: approved, lgtm

#1208 [konflux] increase build queue size
  doozer/doozerlib/constants.py
Labels: approved, lgtm

#1211 Add KonfluxRecord.__repr__ to help displaying of builds in debugger
  artcommon/artcommonlib/konflux/konflux_build_record.py
Labels: lgtm

#1214 [konflux] skip SBOM components with incorrect purl
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm, tide/merge-method-squash

#1212 Improve scan-sources-konflux
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1213 [konflux] allow field to override konflux template url
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/constants.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1215 ocp4-scan-konflux: only look at Konflux builds by default
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1222 doozer: Don't send HTTP requests in unit test
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm

#1225 trigger rhcos_sync with shortname
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#1224 cosign creds fix microshift bootc
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/constants.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
Labels: approved, lgtm

#1204 avoid forwarding user-supplied headers unconditionally
  art-cluster/cloudflare/package-lock.json
  art-cluster/cloudflare/package.json
  art-cluster/cloudflare/src/index.ts
Labels: approved, lgtm

#1170 Make quay-doomsday-backup async and send its results to Slack
  pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm

#1227 Elliott: Fix unit tests that take too much time
  elliott/elliottlib/errata.py
  elliott/tests/test_brew.py
Labels: approved, lgtm

#1226 pyartcd unit test fixes and cleanups
  pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
  pyartcd/requirements.txt
  pyartcd/tests/pipelines/test_gen_assembly.py
  pyartcd/tests/pipelines/test_promote.py
  pyartcd/tests/test_rebuild_golang_rpms.py
  pyartcd/tests/test_signatory.py
Labels: approved, lgtm

#1228 Fix schema for ci_build_root
  ocp-build-data-validator/validator/json_schemas/image_content.requires.schema.json
Labels: approved, lgtm

#1104 ART-11093 add ignore_non_x86_nightlies arg for gen-assembly
  artcommon/artcommonlib/constants.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/tests/cli/test_gen_assembly.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm, tide/merge-method-squash

#1223 ART-11638 remove art-ci
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/build-config.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/cluster-role-binding.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/event-listener.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/image-stream.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/pipeline.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/route.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/service.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/task.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/trigger-binding.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/trigger-template.yaml
Labels: approved, lgtm

#1234 update scan-sources:noop logic
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1231 ART-11446: images-health should report only failures
  doozer/doozerlib/cli/images_health.py
Labels: jira/valid-reference

#1240 [konflux] override dockerfile after digest calculation
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm
