Repository openshift-eng/art-tools, pull requests merged in 2024-03, with the labels that each got.

#441 RHCOS build id from new label if present
  doozer/doozerlib/rhcos.py
Labels: approved, lgtm

#440 Fix elliott find-builds
  artcommon/artcommonlib/build_util.py
  doozer/doozerlib/distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/metadata.py
  elliott/tests/test_metadata.py
Labels: approved, lgtm

#431 Set SKIP_PLASHETS to False for scheduled ocp4 builds
  pyartcd/pyartcd/jenkins.py
Labels: approved, lgtm

#444 Pin pytest to 8.0.2
  doozer/requirements-dev.txt
  pyartcd/requirements-dev.txt
Labels: approved, lgtm

#443 Do not merge alternative_config if ART and upstream el versions match
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#432 Purge elliottlib/model.py and doozerlib/model.py
  doozer/doozerlib/brew.py
  doozer/doozerlib/cli/get_nightlies.py
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/dblib.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/model.py
  doozer/doozerlib/plashet.py
  doozer/doozerlib/repos.py
  doozer/doozerlib/rhcos.py
  doozer/doozerlib/rpm_builder.py
  doozer/doozerlib/rpmcfg.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/source_modifications.py
  doozer/doozerlib/util.py
  doozer/tests/cli/test_config_tag_rpms.py
  doozer/tests/cli/test_gen_assembly.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/cli/test_get_nightlies.py
  doozer/tests/cli/test_scan_sources.py
  doozer/tests/test_assembly_inspector.py
  doozer/tests/test_distgit/support.py
  doozer/tests/test_distgit/test_generic_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tests/test_distgit/test_rpm_distgit.py
  doozer/tests/test_image.py
  doozer/tests/test_metadata.py
  doozer/tests/test_plashet.py
  doozer/tests/test_rhcos.py
  doozer/tests/test_runtime.py
  doozer/tests/test_util.py
  doozer/tests_functional/test_sanity.py
  elliott/elliottlib/brew.py
  elliott/elliottlib/build_finder.py
  elliott/elliottlib/metadata.py
  elliott/elliottlib/model.py
  elliott/elliottlib/runtime.py
  elliott/tests/test_build_finder.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/util.py
Labels: lgtm

#445 changed parameter name ocp_build_data_url to data_path
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#449 Make scan-sources alternative_upstream aware
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/metadata.py
Labels: approved, lgtm

#450 Move dotconfig to artcommonlib
  artcommon/artcommonlib/dotconfig.py
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/dotconfig.py
  doozer/rundoozer/rundoozer
  elliott/elliottlib/cli/common.py
Labels: approved, lgtm

#428 Fix Referenced before assignment error
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
Labels: lgtm

#451 Fix owners when None
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#410 [ART-8970] Mirror all images to private quay
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: lgtm

#452 Move pushd to artcommon
  artcommon/artcommonlib/pushd.py
  artcommon/tests/test_pushd.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/comment_on_pr.py
  doozer/doozerlib/config.py
  doozer/doozerlib/coverity.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/exectools.py
  doozer/doozerlib/gitdata.py
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/olm/bundle.py
  doozer/doozerlib/rpmcfg.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/source_modifications.py
  doozer/tests/test_exectools.py
  elliott/elliottlib/exectools.py
  elliott/elliottlib/gitdata.py
  elliott/elliottlib/pushd.py
  elliott/tests/test_exectools.py
  elliott/tests/test_pushd.py
Labels: approved, lgtm

#454 Move exectools to artcommon
  artcommon/artcommonlib/exectools.py
  artcommon/tests/test_exectools.py
  doozer/doozerlib/brew.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/config_tag_rpms.py
  doozer/doozerlib/cli/detect_embargo.py
  doozer/doozerlib/cli/get_nightlies.py
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/cli/scan_osh.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/coverity.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/exceptions.py
  doozer/doozerlib/gitdata.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/olm/bundle.py
  doozer/doozerlib/osbs2_builder.py
  doozer/doozerlib/rhcos.py
  doozer/doozerlib/rpm_builder.py
  doozer/doozerlib/rpmcfg.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/source_modifications.py
  doozer/doozerlib/util.py
  doozer/tests/cli/test_detect_embargo.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/cli/test_rpms_build.py
  doozer/tests/cli/test_scan_sources.py
  doozer/tests/test_brew_inspector.py
  doozer/tests/test_distgit/test_pull_image.py
  doozer/tests/test_image.py
  doozer/tests/test_osbs2.py
  doozer/tests/test_rhcos.py
  doozer/tests/test_rpm_builder.py
  doozer/tests/test_runtime.py
  doozer/tests_functional/__init__.py
  doozer/tests_functional/test_sanity.py
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/find_unconsumed_rpms.py
  elliott/elliottlib/cli/rhcos_cli.py
  elliott/elliottlib/cli/verify_attached_operators_cli.py
  elliott/elliottlib/cli/verify_cvp_cli.py
  elliott/elliottlib/cvp.py
  elliott/elliottlib/errata_async.py
  elliott/elliottlib/exectools.py
  elliott/elliottlib/gitdata.py
  elliott/elliottlib/rhcos.py
  elliott/elliottlib/util.py
  elliott/tests/test_exectools.py
  elliott/tests/test_verify_attached_operators.py
  pyartcd/pyartcd/exectools.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#457 Fix elliott metadata testcase
  elliott/tests/test_metadata.py
Labels: approved, lgtm

#459 olm-bundle:rebase-and-build clone distgits if needed
  doozer/doozerlib/cli/olm_bundle.py
Labels: approved, lgtm

#458 Tag rpms spam on a schedule
  artcommon/artcommonlib/util.py
  artcommon/tests/test_util.py
  doozer/doozerlib/util.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/tag_rpms.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#461 olm-bundle: clone distgits when needed do not prevent cloning
  doozer/doozerlib/cli/olm_bundle.py
Labels: lgtm

#463 Fallback to RHCOS org.opencontainers.image.version label
  elliott/elliottlib/cli/rhcos_cli.py
Labels: approved, lgtm

#464 Consolidate get_build_id_from_rhcos_pullspec() into artcommon
  artcommon/artcommonlib/rhcos.py
  doozer/doozerlib/rhcos.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/rhcos_cli.py
Labels: approved, lgtm

#466 Fix jenkins URLs for new buildvm
  pyartcd/pyartcd/jenkins.py
Labels: approved

#468 Do not double init logging
  doozer/doozerlib/runtime.py
Labels: approved, lgtm

#470 Fix jenkins urls for cleanup locks
  pyartcd/pyartcd/constants.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/cleanup_locks.py
Labels: approved, lgtm

#453 Use secure xml parser
  doozer/doozerlib/repodata.py
  doozer/tests/test_repodata.py
Labels: lgtm

#477 Gen payload fix auth path
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm

#478 fix reposync
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#479 plashet: Use queryRPMSigs API to check if rpm signed
  doozer/doozerlib/cli/config_plashet.py
Labels: approved, lgtm

#480 create reposync dirs if not exist
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#482 is_signed: check brew on nvr rather than nvre
  doozer/doozerlib/cli/config_plashet.py
Labels: approved, lgtm

#481 Fix repodirs
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#483 build-sync: Fix registry auth again
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#484 Include auth in all manifest tool push from-spec
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: tide/merge-method-squash

#485 fix operator_sdk_sync job
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
Labels: approved, lgtm

#488 Provide manifest-tool with authorization option
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#465 multi-rhel oc-mirror
  pyartcd/pyartcd/oc.py
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#489 ART-9243 Remove "buildroot change" rebuild reason for images
  doozer/doozerlib/image.py
Labels: approved, lgtm

#492 promote: Fix oc-mirror extraction
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#490 refactor kerberos to artcommon
  .devcontainer/Containerfile
  artcommon/configs/krb5-redhat.conf
  doozer/.devcontainer/dev.Dockerfile
  doozer/.devcontainer/docker-compose.yaml
  doozer/.devcontainer/krb5-redhat.conf
  elliott/.devcontainer/docker-compose.yaml
  elliott/.devcontainer/krb5-redhat.conf
  ocp-build-data-validator/.devcontainer/docker-compose.yaml
Labels: approved, lgtm

#495 Enable jinja autoescape
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#486 Do not fetch the release date for custom assemblies
  artcommon/artcommonlib/util.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#494 Define a manifest-tool wrapper function
  artcommon/artcommonlib/exectools.py
  doozer/doozerlib/cli/release_gen_payload.py
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#499 [ART-7053] Use JIRA field names
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/find_bugs_kernel_cli.py
  elliott/elliottlib/cli/find_bugs_kernel_clones_cli.py
  elliott/elliottlib/constants.py
  elliott/tests/test_find_bugs_kernel_cli.py
  elliott/tests/test_find_bugs_kernel_clones_cli.py
Labels: approved, lgtm

#506 ART-9251: olm_bundle: Fix operand name resolution
  doozer/doozerlib/image.py
  elliott/elliottlib/imagecfg.py
Labels: approved, lgtm, jira/valid-reference

#505 find-builds: Report on all found builds
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#511 Cleanup reposync command
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#512 also sync noarch rpm
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#514 latest_build_list(): log the search pattern when no builds are found
  doozer/doozerlib/metadata.py
  elliott/elliottlib/metadata.py
Labels: approved, lgtm

#515 config tweak
  ocp-build-data-validator/validator/github.py
Labels: approved, lgtm

#509 [ART-8482] Add labels for better JIRA tracking
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#518 Populate all non-modular rpms
  doozer/doozerlib/repodata.py
Labels: approved, lgtm
