Repository openshift-eng/art-tools, pull requests merged in 2024-02, with the labels that each got.

#369 Fix slack reaction error
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm

#370 Fix rebase with a deep_merge() function
  artcommon/artcommonlib/util.py
  artcommon/tests/test_util.py
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#354 RC did not react, double waiting time
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#373 Add pipeline list role for art-cd
  art-cluster/pipelines/config/argocd/project/art-cd/common/pipeline-list-role.yaml
  art-cluster/pipelines/config/argocd/project/art-cd/common/pipeline-list-rolebinding.yaml
Labels: approved, lgtm

#374 doozer images:streams - fix golang version problem
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#376 report nothing when list of inconsistencies is empty
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#380 Fix imports and pin openshift-client lib
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/requirements.txt
  doozer/tests/cli/test_gen_payload.py
  pyartcd/pyartcd/oc.py
  pyartcd/pyartcd/pipelines/build_rhcos.py
  pyartcd/requirements.txt
Labels: approved, lgtm

#375 build-sync: skip unwanted operations when running a dry run
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: lgtm

#361 [ART-6890] Allow stream aliases and multi-branch image builds
  artcommon/tests/test_util.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/brew_info.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/olm/bundle.py
  doozer/doozerlib/repos.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/util.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/test_brew_inspector.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tests/test_image.py
  doozer/tests/test_osbs2.py
  elliott/elliottlib/metadata.py
  elliott/tests/test_metadata.py
Labels: approved, lgtm

#382 Allow name attribute in distgit
  ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json
Labels: lgtm

#383 Clean _determine_upstream_rhel_version() leftovers
  doozer/doozerlib/distgit.py
Labels: lgtm

#381 Remove go.real symlink
  doozer/doozerlib/go.real
Labels: approved, lgtm

#384 Add missing branch_el_target func in elliott
  elliott/elliottlib/metadata.py
Labels: lgtm

#386 Fix validator
  ocp-build-data-validator/validator/json_schemas/streams.schema.json
  ocp-build-data-validator/validator/schema/streams_schema.py
Labels: approved, lgtm

#387 Update metadata.config after merging alternative_upstream
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#341 [ART-8765] Prepare prepare-release to handle advance operator release
  artcommon/artcommonlib/exceptions.py
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/tests/test_find_bugs_sweep_cli.py
  pyartcd/pyartcd/exceptions.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#378 spdlog: Get two versions in plashet
  pyartcd/pyartcd/plashets.py
Labels: approved, lgtm

#390 fix date format
  artcommon/artcommonlib/util.py
Labels: approved, lgtm

#391 set operator_bundle_advisory default value to metadata
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
Labels: approved, lgtm

#394 Use .el<version> suffix to find Brew builds
  doozer/doozerlib/metadata.py
  elliott/elliottlib/metadata.py
Labels: approved, lgtm

#395 Clone distgits to allow merging configs during gen-payload
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#398 build-sync: fix runtime initialization
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#403 [ART-8912] Skip ocp-build-data for pr in build feature
  doozer/doozerlib/comment_on_pr.py
Labels: approved, lgtm

#397 Gather builds before bug sweep
  elliott/elliottlib/cli/find_builds_cli.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved

#405 Prevent canonical upstream for non-stream images
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#402 Use multiple search patterns when looking for builds
  doozer/doozerlib/metadata.py
  doozer/tests/cli/test_rpms_build.py
  doozer/tests/test_metadata.py
  doozer/tests/test_rpm_builder.py
Labels: approved, lgtm

#413 Use multiple search patterns when looking for builds
  doozer/doozerlib/metadata.py
  elliott/elliottlib/metadata.py
Labels: approved, lgtm

#415 Use yaml.safe_load instead of yaml.load
  pyartcd/pyartcd/pipelines/operator_sdk_sync.py
Labels: approved, lgtm

#417 Fix rhel pattern when None
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
Labels: lgtm

#420 Enforce distgits cloning when canonical_builders is enabled
  doozer/doozerlib/runtime.py
Labels: lgtm

#419 Honor canonical builders from upstream in gen-assembly
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: lgtm

#422 Honor canonical builder in elliott find-builds
  doozer/doozerlib/runtime.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/runtime.py
Labels: approved, lgtm

#426 Fix doozer runtime initialization
  doozer/doozerlib/runtime.py
Labels: approved, lgtm

#429 Move assembly.py to artcommon
  artcommon/artcommonlib/assembly.py
  artcommon/tests/test_assembly.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/config_tag_rpms.py
  doozer/doozerlib/cli/inspect_stream.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/plashet.py
  doozer/doozerlib/rpmcfg.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/util.py
  doozer/tests/cli/test_config_tag_rpms.py
  doozer/tests/cli/test_gen_assembly.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/test_assembly.py
  doozer/tests/test_assembly_inspector.py
  doozer/tests/test_distgit/support.py
  doozer/tests/test_distgit/test_generic_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_push_image.py
  elliott/elliottlib/assembly.py
  elliott/elliottlib/build_finder.py
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/cli/find_bugs_kernel_cli.py
  elliott/elliottlib/cli/find_bugs_kernel_clones_cli.py
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/find_unconsumed_rpms.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/metadata.py
  elliott/elliottlib/runtime.py
  elliott/tests/test_find_bugs_kernel_cli.py
  elliott/tests/test_find_bugs_kernel_clones_cli.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/rebuild.py
  pyartcd/pyartcd/util.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#433 gen-payload: specify build target when looking at image builds
  doozer/doozerlib/assembly_inspector.py
Labels: approved, lgtm

#430 fix ref task name
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/pipeline.yaml
Labels: lgtm

#434 Build sync wait longer
  doozer/doozerlib/cli/release_gen_payload.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#435 [ART-8910] Always inject doozer metadata environment variables on rebase
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#427 Move logutil to art-common
  artcommon/artcommonlib/logutil.py
  doozer/doozerlib/brew.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/cli/get_nightlies.py
  doozer/doozerlib/comment_on_pr.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/exectools.py
  doozer/doozerlib/gitdata.py
  doozer/doozerlib/logutil.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/plashet.py
  doozer/doozerlib/repodata.py
  doozer/doozerlib/rhcos.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/source_modifications.py
  doozer/tests/test_rpmcfg.py
  doozer/tests/test_runtime.py
  elliott/elliottlib/brew.py
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/advisory_commons_cli.py
  elliott/elliottlib/cli/attach_bugs_cli.py
  elliott/elliottlib/cli/create_placeholder_cli.py
  elliott/elliottlib/cli/create_textonly_cli.py
  elliott/elliottlib/cli/find_bugs_qe_cli.py
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/get_golang_report_cli.py
  elliott/elliottlib/cli/get_golang_versions_cli.py
  elliott/elliottlib/cli/move_builds_cli.py
  elliott/elliottlib/cli/remove_bugs_cli.py
  elliott/elliottlib/cli/remove_builds_cli.py
  elliott/elliottlib/cli/tarball_sources_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/errata.py
  elliott/elliottlib/errata_async.py
  elliott/elliottlib/exectools.py
  elliott/elliottlib/imagecfg.py
  elliott/elliottlib/metadata.py
  elliott/elliottlib/runtime.py
  elliott/elliottlib/tarball_sources.py
Labels: approved, lgtm

#438 Fix elliott
  elliott/elliottlib/cli/create_cli.py
Labels: approved, lgtm

#439 Remove unused import
  elliott/elliottlib/cli/create_cli.py
Labels: approved
