Repository openshift-eng/art-tools, pull requests merged in 2024-01, with the labels that each got.

#283 Move duplicated functions to artcommon
  artcommon/artcommonlib/build_util.py
  artcommon/artcommonlib/release_util.py
  artcommon/tests/test_util.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/cli/config_tag_rpms.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/olm/bundle.py
  doozer/doozerlib/plashet.py
  doozer/doozerlib/rhcos.py
  doozer/doozerlib/rpm_builder.py
  doozer/doozerlib/util.py
  doozer/tests/test_util.py
  elliott/elliottlib/build_finder.py
  elliott/elliottlib/util.py
  elliott/tests/test_util.py
Labels: lgtm

#286 Fix slack function. Skip sending qe notification for ECs and RCs
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm

#287 [scan-osh] Fix JIRA search query issue and update regex
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#284 Move formatting utils to artcommon
  artcommon/artcommonlib/format_util.py
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/config.py
  doozer/doozerlib/cli/detect_embargo.py
  doozer/doozerlib/cli/get_nightlies.py
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_osh.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/exectools.py
  doozer/doozerlib/util.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/advisory_commons_cli.py
  elliott/elliottlib/cli/change_state_cli.py
  elliott/elliottlib/cli/common.py
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/cli/create_textonly_cli.py
  elliott/elliottlib/cli/find_bugs_blocker_cli.py
  elliott/elliottlib/cli/find_bugs_kernel_cli.py
  elliott/elliottlib/cli/find_bugs_kernel_clones_cli.py
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/get_golang_versions_cli.py
  elliott/elliottlib/cli/remove_bugs_cli.py
  elliott/elliottlib/cli/repair_bugs_cli.py
  elliott/elliottlib/cli/rhcos_cli.py
  elliott/elliottlib/cli/tag_builds_cli.py
  elliott/elliottlib/cli/tarball_sources_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/cli/verify_attached_operators_cli.py
  elliott/elliottlib/cli/verify_cvp_cli.py
  elliott/elliottlib/errata.py
  elliott/elliottlib/rhcos.py
  elliott/elliottlib/util.py
Labels: approved, lgtm

#285 gen-assembly: Ignore outdated payload tag
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: approved, lgtm

#290 Allow to override pscomponent label for CVE trackers
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#291 [ART-8625] skip populating rpm advisory, if prerelease
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#296 [prerelease] remove operator index mode group.yml
  doozer/doozerlib/olm/bundle.py
Labels: approved, lgtm

#298 [scan-osh] Don't clone source for rpms
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#299 doozer olm/bundle: ga-plus explanation
  doozer/doozerlib/olm/bundle.py
Labels: approved, lgtm

#300 [scan-osh] update regex for microshift nightly
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#302 [scan-osh] Fix container classification bug
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#281 Omit disabled repos from .oit/{signed,unsigned}.repo during rebase
  doozer/doozerlib/repos.py
Labels: approved, lgtm

#301 Add the __repr__ method to let the distgit name appears while debugging
  doozer/doozerlib/distgit.py
Labels: lgtm

#309 support bug close status with Obsolete
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
Labels: approved, lgtm

#310 Fix prerelease flag logic
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#311 gen-assembly: Update advisories with ones inherited
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: approved, lgtm

#313 skip verify-flaws for preview and prerelease
  pyartcd/pyartcd/pipelines/promote.py
Labels: lgtm

#276 ART-8426 Find golang trackers and determine if they are fixed
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/find_bugs_golang_cli.py
  elliott/elliottlib/runtime.py
  elliott/elliottlib/util.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved

#321 Pass reposync enabled repos to invocation
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#322 Fix reposync good now
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#312 elliott - remove builds cli
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/remove_builds_cli.py
  elliott/elliottlib/cli/verify_attached_operators_cli.py
Labels: approved, lgtm

#328 Run flake8 and unit tests against validator as well
  Makefile
Labels: approved, lgtm

#314 no_verify_blocking_bugs for EC, RC and first GA
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#334 Update images health message
  pyartcd/pyartcd/pipelines/images_health.py
Labels: approved, lgtm

#336 [ART-7423] Migrate ocp build data validator
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/build-config.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/cluster-role-binding.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/event-listener.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/image-stream.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/pipeline.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/route.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/service.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/task.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/trigger-binding.yaml
  art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/trigger-template.yaml
  ocp-build-data-validator/Dockerfile
  ocp-build-data-validator/entrypoint.sh
Labels: approved, lgtm

#338 Set GOTOOLCHAIN to local in rpm wrapper
  doozer/doozerlib/rpm_builder_go_wrapper.sh
Labels: approved, lgtm

#339 [ART-8764] Setup advance operator release
  doozer/doozerlib/cli/release_gen_assembly.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
  pyartcd/tests/pipelines/test_gen_assembly.py
Labels: approved

#344 Ignore outdated_rpms_in_stream_build assembly issue for RC inconsistency
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#343 ART-8758 Leave advisory type comment if configured
  elliott/elliottlib/cli/create_cli.py
Labels: lgtm

#332 [ART-8241] Backup promoted payloads to AWS
  pyartcd/pyartcd/pipelines/promote.py
Labels: lgtm, do-not-merge/hold

#347 Backup promoted payloads to AWS
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#349 Only retry on TryAgain exception type
  pyartcd/pyartcd/locks.py
Labels: approved, lgtm

#342 ART-8476 canonical builders
  doozer/doozerlib/distgit.py
  doozer/tests/test_distgit/test_generic_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_push_image.py
Labels: approved, lgtm

#355 Allow pipeline user to trigger tekton pipelines
  art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/cluster-role-binding.yaml
Labels: approved, lgtm

#358 bashlex uses POSIX-1834 standard
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#360 [tekton] Remove event-listener resources
  art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/event-listener.yaml
  art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/route.yaml
  art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/service.yaml
  art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/trigger-binding.yaml
  art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/trigger-template.yaml
Labels: approved, lgtm

#362 Improve logs when trying to merge configs during rebase
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#363 log severity change
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#364 Use canonical builders when rhel versions match
  artcommon/artcommonlib/util.py
  artcommon/tests/test_util.py
  doozer/doozerlib/distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
Labels: approved, lgtm

#365 Allow ocp4-scan to ignore locks
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: lgtm

#327 Fix GhApi owner param
  pyartcd/pyartcd/constants.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/review_cvp.py
Labels: approved, lgtm

#366 Set default lock timeout to a BIG value
  pyartcd/pyartcd/locks.py
  pyartcd/tests/test_locks.py
Labels: approved, lgtm

#367 Fix rebase
  doozer/doozerlib/distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
Labels: approved, lgtm

#368 [ART-8800] update alignment PR wording
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm
