Repository openshift-eng/art-tools, pull requests merged in 2024-07, with the labels that each got.

#718 [ART-9923] support dockerfile_fallback field
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/util.py
Labels: approved, lgtm

#736 Init elliott debug.log
  elliott/elliottlib/runtime.py
Labels: approved, lgtm

#737 Ignore cve if fixed_in_version not found
  elliott/elliottlib/cli/find_bugs_golang_cli.py
Labels: lgtm

#738 Fix dry-run invocation
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#740 Update-golang can update streams.yml
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#741 plashets: Double waiting minutes to 30
  doozer/doozerlib/cli/config_plashet.py
Labels: approved, lgtm

#746 Add identity when using cosign
  pyartcd/pyartcd/signatory.py
Labels: approved, lgtm

#735 Refactor Runtime
  artcommon/artcommonlib/git_helper.py
  artcommon/artcommonlib/lock.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/cli/images_okd.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/coverity.py
  doozer/doozerlib/dblib.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/k_distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/record_logger.py
  doozer/doozerlib/rpmcfg.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/source_resolver.py
  doozer/doozerlib/util.py
  doozer/requirements.txt
  doozer/tests/test_dblib.py
  doozer/tests/test_distgit/support.py
  doozer/tests/test_distgit/test_generic_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_push_image.py
  doozer/tests/test_metadata.py
  doozer/tests/test_runtime.py
  doozer/tests/test_source_resolver.py
  elliott/elliottlib/runtime.py
  elliott/pyproject.toml
  pyartcd/requirements.txt
Labels: lgtm

#752 Revert refactoring
  artcommon/artcommonlib/git_helper.py
  artcommon/artcommonlib/lock.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/cli/images_okd.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/coverity.py
  doozer/doozerlib/dblib.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/k_distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/record_logger.py
  doozer/doozerlib/rpmcfg.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/source_resolver.py
  doozer/doozerlib/util.py
  doozer/requirements.txt
  doozer/tests/test_dblib.py
  doozer/tests/test_distgit/support.py
  doozer/tests/test_distgit/test_generic_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_push_image.py
  doozer/tests/test_metadata.py
  doozer/tests/test_runtime.py
  doozer/tests/test_source_resolver.py
  elliott/elliottlib/runtime.py
  elliott/pyproject.toml
  pyartcd/requirements.txt
Labels: approved, lgtm

#753 Bump signing timeout radically
  doozer/doozerlib/cli/config_plashet.py
Labels: approved, lgtm

#755 Fix _is_pub_ancestor_of_priv
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#743 Update streams.yml for other versions that might have builder
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: tide/merge-method-squash

#757 ART-9182 Trigger rhcos_sync for ECs and GA
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#703 verify-bugs: Report consistently
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm

#764 Do not attempt to move microshift advisory to QE
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, tide/merge-method-squash

#767 Remove runtime.logger refs in elliott
  elliott/elliottlib/brew.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/elliottlib/cli/find_bugs_blocker_cli.py
  elliott/elliottlib/cli/find_bugs_golang_cli.py
  elliott/elliottlib/cli/find_bugs_kernel_cli.py
  elliott/elliottlib/cli/find_bugs_kernel_clones_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/find_unconsumed_rpms.py
  elliott/elliottlib/cli/rhcos_cli.py
  elliott/elliottlib/cli/tag_builds_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/cli/verify_cvp_cli.py
  elliott/elliottlib/metadata.py
  elliott/tests/test_early_kernel.py
  elliott/tests/test_metadata.py
Labels: approved, lgtm, tide/merge-method-squash

#769 Run golang bug sweep as part of ocp4
  elliott/elliottlib/cli/find_bugs_golang_cli.py
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#772 Fix resolve dockerfile name
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/util.py
Labels: approved, lgtm

#771 Skip test builds in FIPS scan
  doozer/doozerlib/cli/scan_fips.py
Labels: approved, lgtm

#773 [sast pipeline] update test build filtering logic
  doozer/doozerlib/cli/scan_osh.py
Labels: approved, lgtm

#783 rollback fallback
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/metadata.py
Labels: approved, lgtm

#785 Fix get_latest_build patterns
  doozer/doozerlib/metadata.py
  elliott/elliottlib/metadata.py
Labels: approved, lgtm, tide/merge-method-squash

#786 Exempt rpms properly
  doozer/doozerlib/image.py
Labels: approved, lgtm

#789 Fix el_ver parsing
  doozer/doozerlib/metadata.py
  elliott/elliottlib/metadata.py
Labels: approved, lgtm

#728 removed early-kernel-ship-ok tag
  artcommon/artcommonlib/assembly.py
  doozer/doozerlib/cli/config_tag_rpms.py
  doozer/doozerlib/rpm_delivery.py
  doozer/tests/cli/test_config_tag_rpms.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/test_assembly_inspector.py
Labels: approved, lgtm

#788 Increase verbosity remove from batch logic
  elliott/elliottlib/errata.py
Labels: approved, lgtm, tide/merge-method-squash

#749 [chore] fix dev container configuration
  .devcontainer/Containerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yaml
Labels: approved, lgtm

#784 Allow multiple comments on pr
  doozer/doozerlib/comment_on_pr.py
  doozer/tests/test_comment_on_pr.py
Labels: approved, lgtm, tide/merge-method-squash

#792 Don't set publish date if batch is provided
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/errata_async.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm, tide/merge-method-squash

#795 Revert "Don't set publish date if batch is provided"
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/errata_async.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#797 [fips scan] bump setuptools
  art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml
Labels: approved, lgtm

#796 Fix cloudflare sync
  pyartcd/pyartcd/util.py
Labels: lgtm

#798 Add logging to scan-sources
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#497 send release complete from script
  pyartcd/config.example.toml
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: lgtm, tide/merge-method-squash

#799 Raise on verify-attached-operators fail
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#745 ART-9443 update extract_opm to support multi rhel binaries
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, tide/merge-method-squash

#756 Re-apply Runtime refactoring with fixes for cloning public upstream repo
  artcommon/artcommonlib/git_helper.py
  artcommon/artcommonlib/lock.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/images_okd.py
  doozer/doozerlib/cli/images_streams.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/coverity.py
  doozer/doozerlib/dblib.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/k_distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/record_logger.py
  doozer/doozerlib/rpmcfg.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/source_resolver.py
  doozer/doozerlib/util.py
  doozer/requirements.txt
  doozer/tests/test_dblib.py
  doozer/tests/test_distgit/support.py
  doozer/tests/test_distgit/test_generic_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tests/test_distgit/test_image_distgit/test_push_image.py
  doozer/tests/test_metadata.py
  doozer/tests/test_runtime.py
  doozer/tests/test_source_resolver.py
  elliott/elliottlib/runtime.py
  elliott/pyproject.toml
  pyartcd/requirements.txt
Labels: approved, do-not-merge/hold

#800 Only alert when advisory cannot move from new_files to qe
  elliott/elliottlib/cli/change_state_cli.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm, tide/merge-method-squash

#805 update-golang Revert template changes for rhel7/9
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#806 Fix olm bundle command init
  doozer/doozerlib/cli/olm_bundle.py
Labels: approved, lgtm

#808 [fips-scan] allow test builds
  doozer/doozerlib/cli/scan_fips.py
Labels: approved, lgtm

#807 invalidate cloudfront cache during promote
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#801 Don't set publish date if batch is provided
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/errata_async.py
  elliott/elliottlib/util.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm, tide/merge-method-squash

#810 Move rpm_utils to artcommon
  artcommon/artcommonlib/rpm_utils.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/plashet.py
  doozer/doozerlib/repodata.py
  doozer/doozerlib/rpmcfg.py
  doozer/tests/test_repodata.py
  doozer/tests/test_rpm_utils.py
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/elliottlib/cli/find_bugs_golang_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/get_golang_report_cli.py
  elliott/elliottlib/cli/get_golang_versions_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/errata_async.py
  elliott/elliottlib/rpm_utils.py
  elliott/tests/test_errata_async.py
  pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#811 [golang builder] rename yaml safe_load to load
  doozer/doozerlib/source_resolver.py
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#804 Fix a bug in image embargo detection
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/rpmcfg.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
Labels: approved, lgtm
