Repository openshift-eng/art-tools, pull requests merged in 2024-05, with the labels that each got.

#558 elliott find-bugs:golang enhancements
  elliott/elliottlib/build_finder.py
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/find_bugs_golang_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/pyproject.toml
Labels: tide/merge-method-squash

#561 use branch in image config
  doozer/doozerlib/olm/bundle.py
Labels: approved, lgtm, tide/merge-method-squash

#582 Get missing bundle branches first
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/olm/bundle.py
  doozer/tests/test_olm_bundle.py
Labels: tide/merge-method-squash

#608 Select existing bundle image for assembly if delivery labels match
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/olm/bundle.py
  doozer/tests/test_olm_bundle.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved

#613 Fix rhcos validator
  ocp-build-data-validator/validator/json_schemas/assembly_group_config.schema.json
  ocp-build-data-validator/validator/json_schemas/rhcos.schema.json
Labels: approved, lgtm

#583 ART-9558: Use -rhel9 for dynamic installer build in 4.16
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, jira/valid-reference

#614 Use art automation address for art image build fail emails
  pyartcd/pyartcd/util.py
Labels: approved, lgtm, tide/merge-method-squash

#580 Add owners support to images:print
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#620 compression log for build_sync
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#615 Cleanup prepare-release logs
  artcommon/artcommonlib/exectools.py
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#621 Fix olm bundle invocations
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/olm/bundle.py
Labels: approved, lgtm

#623 fix find-bundle function
  doozer/doozerlib/cli/olm_bundle.py
  pyartcd/pyartcd/pipelines/scan_fips.py
Labels: tide/merge-method-squash

#629 Error out when verify attached operator fails
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: tide/merge-method-squash

#632 gen-assembly: notify when non-latest green amd64 nightly is selected
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#634 Validate cdn repos
  elliott/elliottlib/cli/find_builds_cli.py
Labels: lgtm

#638 fix find build return value
  doozer/doozerlib/cli/olm_bundle.py
Labels: approved, lgtm

#639 plashets: default to rhel7 if no el version is specified in the NVR
  doozer/doozerlib/cli/config_plashet.py
Labels: approved, lgtm

#643 allow EMBARGOED_CONTENT in standard permits
  artcommon/artcommonlib/assembly.py
Labels: approved, lgtm, tide/merge-method-squash

#644 Skip metadata population during pre-release
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm, tide/merge-method-squash

#645 Dont try to read stdin by default
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/remove_builds_cli.py
Labels: approved, lgtm

#650 golang builder append --push bug
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#652 [fips-cluster] pin pip packages to task
  art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml
Labels: approved, lgtm

#647 rpm fips wrapper: Explicitly allow no CGO for GOOS=windows
  doozer/doozerlib/rpm_builder_go_wrapper.sh
Labels: approved, lgtm

#448 Match upstream builders by finding a suitable entry in streams.yml
  doozer/doozerlib/distgit.py
  doozer/tests/test_distgit/test_resolve_image_from_upstream_parent.py
Labels: approved, lgtm

#637 ART-9595: Document known limitation in golang bump prs
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#657 set custom cert for konflux
  doozer/doozerlib/constants.py
  doozer/doozerlib/k_distgit.py
  doozer/doozerlib/repos.py
Labels: approved, lgtm, tide/merge-method-squash

#658 [konflux] fix Dockerfile step, sslcacert only for ocp-artifacts
  doozer/doozerlib/k_distgit.py
  doozer/doozerlib/repos.py
Labels: approved, lgtm

#660 Optimize overrides, use brew registry for Konflux
  doozer/doozerlib/constants.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/k_distgit.py
Labels: approved, lgtm

#659 Respect cachito global config
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#651 Update golang script tweaks
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: lgtm, tide/merge-method-squash
