Repository openshift-eng/art-tools, pull requests merged in 2024-04, with the labels that each got.

#516 [ART-8971] Mirror non-embargoed images to public quay
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm, tide/merge-method-squash

#520 Fix oc-mirror extraction again
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#522 Refactor check bugs
  pyartcd/pyartcd/pipelines/check_bugs.py
  pyartcd/tests/pipelines/test_check_bugs.py
Labels: approved, lgtm

#528 Make sure assembly name matches found microshift build
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: lgtm

#532 Do not reinit group_commitish
  doozer/doozerlib/runtime.py
Labels: approved, lgtm

#535 [ART-9390] repodata directory was not being created in constructed repo
  doozer/doozerlib/cli/__main__.py
Labels: approved, lgtm

#536 Fix unit tests
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm

#538 Honor build data commit in build-sync
  doozer/doozerlib/gitdata.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#537 Elliott find builds do not look at el target
  doozer/tests/cli/test_gen_payload.py
  elliott/elliottlib/metadata.py
  elliott/tests/test_metadata.py
Labels: approved, lgtm

#542 Verify blocking bugs are attached to an advisory
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
Labels: lgtm

#545 get jira fields with auth
  elliott/elliottlib/bzutil.py
  elliott/tests/test_bzutil.py
  elliott/tests/test_bzutil_jira.py
  elliott/tests/test_find_bugs_blocker_cli.py
  elliott/tests/test_find_bugs_qe_cli.py
  elliott/tests/test_find_bugs_sweep_cli.py
  elliott/tests/test_remove_bugs_cli.py
  elliott/tests/test_repair_bugs_cli.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm

#547 Do not post traceback to slack
  pyartcd/pyartcd/pipelines/gen_assembly.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/pyartcd/pipelines/scan_for_kernel_bugs.py
  pyartcd/pyartcd/pipelines/tag_rpms.py
Labels: approved, lgtm

#549 [ART-9446] Populate jira mappings
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#548 [images:streams] Skip fetching image meta if stream is given
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#551 Ignore dockerfile run options in bashlex
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#559 only check bug for active release
  pyartcd/pyartcd/pipelines/check_bugs.py
Labels: approved, lgtm

#562 Doozer: set completeBefore appropriately when searching for builds
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
Labels: approved, lgtm

#568 Revert "Remove ship-okay tag"
  doozer/doozerlib/rpm_delivery.py
Labels: approved, lgtm

#563 Adjust elliott rhcos to new image label
  elliott/elliottlib/rhcos.py
Labels: lgtm

#569 sudo podman to see root images
  doozer/doozerlib/cli/scan_fips.py
Labels: approved, lgtm

#560 ART-9253 update-golang: Support rebase and build
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: lgtm

#414 ART-8763 create batch when prepare release
  elliott/elliottlib/cli/advisory_drop_cli.py
  elliott/elliottlib/errata.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm, tide/merge-method-squash

#576 Revert "Doozer: set completeBefore appropriately when searching for builds"
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
Labels: approved, lgtm

#578 Workaround for RHELBLD-15024
  doozer/doozerlib/brew.py
  elliott/elliottlib/brew.py
Labels: approved, lgtm
