Repository openshift-eng/art-tools, pull requests merged in 2024-10, with the labels that each got.

#999 Fix images-health
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#996 Start recording konflux builds
  artcommon/artcommonlib/bigquery.py
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/artcommonlib/konflux/konflux_db.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/constants.py
  doozer/doozerlib/distgit.py
  elliott/elliottlib/cli/find_konflux_builds_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1000 Populate parent images + store image tag
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1005 Only scan for Brew builds when checking images health
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#1001 Update konflux rebaser to use BigQuery
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1004 Always lock to datetime.UTC
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/util.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/images_health.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/runtime.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/update_golang.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#1003 Populate installed pkgs in konflux build
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/distgit.py
Labels: approved, lgtm, do-not-merge/hold, tide/merge-method-squash

#1007 Search by distgit_key instead of name
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/runtime.py
  elliott/elliottlib/cli/find_konflux_builds_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1009 Fix store RPM Brew builds in BigQuery
  doozer/doozerlib/cli/rpms.py
Labels: lgtm

#1010 Order buils by end_time DESC (default value for sorting)
  doozer/doozerlib/cli/images_health.py
Labels: lgtm

#997 Migrate doomsday pipeline to python
  art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml
  art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
  art-cluster/pipelines/data/project/art-cd/image/Containerfile.latest
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
Labels: approved, lgtm

#1013 Decrease konflux_db.search_builds_by_fields() log level
  artcommon/artcommonlib/konflux/konflux_db.py
Labels: approved, lgtm

#1016 update file_upload_v2 parameters
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm

#1018 scan-sources: skip unnecessary checks
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#1006 Sleep instead of wait
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#907 Add microshift plashet repo config
  pyartcd/pyartcd/plashets.py
Labels: lgtm

#1022 [konflux] move overrides to code
  doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1008 Log build and rebase exceptions
  doozer/doozerlib/cli/images_konflux.py
Labels: tide/merge-method-squash

#1017 Add extra pattern search to get_latest_build in Konflux
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
Labels: approved, lgtm

#1024 Fix download_file_from_github(); add a retry
  artcommon/artcommonlib/util.py
Labels: approved, lgtm

#1020 deprecate advance release
  doozer/doozerlib/cli/release_gen_assembly.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#1028 images-health: sort builds by start_time
  doozer/doozerlib/cli/images_health.py
Labels: lgtm

#1030 make utc python backwards compatible
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/util.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/images_health.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/runtime.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/update_golang.py
  pyartcd/pyartcd/util.py
Labels: lgtm, tide/merge-method-squash

#1032 ART-10563 Refactor build-microshift pipeline
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/rpm_builder.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm, tide/merge-method-squash

#1033 fix konflux_db dry_run
  doozer/doozerlib/cli/rpms.py
Labels: approved, lgtm

#1034 Log Konflux queries with INFO level
  artcommon/artcommonlib/bigquery.py
Labels: approved, lgtm

#1035 [konflux] DB log print distgit name
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1029 ART-10885 Populate end_time for failed builds with task completion time
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#1039 Log Konflux queries with INFO level
  artcommon/artcommonlib/bigquery.py
Labels: approved, lgtm

#1040 images;health: Tweak message
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#1041 Konflux: make get_latest_build async
  artcommon/artcommonlib/bigquery.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_big_query.py
  artcommon/tests/test_konflux_db.py
Labels: approved, lgtm

#1042 Konflux: Log with stack trace on build error
  doozer/doozerlib/cli/images_konflux.py
Labels: approved, lgtm

#1036 Slow down multi nightly creation
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: approved

#1044 Limit number of concurrent Konflux pipelines
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/constants.py
Labels: approved, lgtm

#1046 Update path object to str
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#1037 ART-10836: Stop publishing rhcos srpms (for now?)
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, jira/valid-reference

#904 [ART-10608] migrate cincinnati job to python
  doozer/requirements.txt
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm, tide/merge-method-squash

#1055 Konflux: Apply addtional-tags for output images
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1048 ART-10999 scan-sources for Konflux: check for upstream changes
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1061 Catch all unsyncd bugs
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1059 Fix konflux_db.get_latest_build calls
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1062 Golang bugs changes to sweep bugs earlier
  elliott/elliottlib/cli/find_bugs_golang_cli.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
  pyartcd/pyartcd/pipelines/update_golang.py
  pyartcd/pyartcd/runtime.py
  pyartcd/tests/test_rebuild_golang_rpms.py
Labels: tide/merge-method-squash

#1068 fix construction of elliott cmd
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#1067 konflux: Fix wrong bundle CSV pullspec with uuid tag
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1069 artcd update-golang: use different working dirs for different el targets
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#1073 [konflux] update konflux log
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1070 Fix shared distgit in concurrent golang bump rpm rebase
  pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
Labels: lgtm

#1049 [art-cluster] quay backup override arches to sync from quay for 4.12 releases
  art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml
  pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
Labels: approved, lgtm, tide/merge-method-squash

#1074 Fix for golang tracker search
  elliott/elliottlib/cli/find_bugs_golang_cli.py
Labels: tide/merge-method-squash

#1077 [konflux] reduce character name for Components
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1076 [konflux] ART-11060 scan for config changes
  artcommon/artcommonlib/util.py
  doozer/doozerlib/cli/images_okd.py
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1078 [konflux] use bigger ppc vm
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1011 ART-10624: set extra fields in reconciliation issues
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm, jira/valid-reference

#1079 [konflux] add ose-prefix
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1063 sync bug with errata before get from errata
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/errata.py
Labels: approved, lgtm, tide/merge-method-squash

#1086 [konflux] restrict arches to x86 temporarily
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1080 ART-10785: accept new_versioning scheme in standard assemably names
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/util.py
  ocp-build-data-validator/validator/json_schemas/releases.schema.json
Labels: approved, lgtm, jira/valid-reference

#1081 ART-10884: accept assembly name with new versioning scheme
  doozer/doozerlib/runtime.py
Labels: approved, lgtm, jira/valid-reference

#1089 [konflux] fix bug arches
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#508 [ART-9249] Set reconciliation bugs as RH employee
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm

#1087 Set multi cadence to 6 hrs
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm, ok-to-test

#1066 ART-10995 fix false alarm for regression check
  artcommon/artcommonlib/util.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1065 [Snyk] Security upgrade mysql-connector-python from 8.0.33 to 9.1.0
  pyartcd/requirements.txt
Labels: approved, lgtm

#1094 ART-11061 Scan for changes in an image's dependencies
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1097 ART-11093 simplify get latest accepted nightly function
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#1098 Raise error on ambiguous streams
  doozer/doozerlib/runtime.py
Labels: lgtm

#1101 Revert "ART-10995 fix false alarm for regression check"
  artcommon/artcommonlib/util.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm

#1102 Fix unbounded variable error for blocker_advisories
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
Labels: approved, lgtm
