Repository openshift-eng/art-tools, pull requests merged in 2025-06, with the labels that each got.

#1640 Build plashets in a dedicated Jenkins job
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
  pyartcd/pyartcd/pipelines/build_plashets.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/tests/pipelines/test_ocp4.py
  pyartcd/tests/pipelines/test_plashets.py
Labels: approved, do-not-merge/hold

#1665 ART-13009 Avoid duplicating plashet builds
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1668 gen-assembly: handle missing payload_name config
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: approved, lgtm

#1659 Add retry option to FIPS scan pipeline
  doozer/doozerlib/cli/scan_fips.py
Labels: approved, lgtm

#1670 ART-13075: Add check for self-referential upgrades
  ocp-build-data-validator/tests/test_releases.py
  ocp-build-data-validator/validator/__main__.py
  ocp-build-data-validator/validator/releases.py
Labels: approved, lgtm, jira/valid-reference

#1673 fix rhcos check in get nightly
  doozer/doozerlib/cli/get_nightlies.py
Labels: approved, lgtm

#1676 fix rhcos version data type
  pyartcd/pyartcd/pipelines/build_plashets.py
Labels: approved, lgtm

#1585 ART-12704 detect rhcos changes in scan sources
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/rhcos.py
  doozer/tests/cli/test_scan_sources.py
  doozer/tests/test_rhcos.py
  pyartcd/pyartcd/pipelines/build_plashets.py
  pyartcd/pyartcd/pipelines/build_rhcos.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm, do-not-merge/hold

#1681 Refactor tests to use MagicMock instead of AsyncMock for verify_connection
  elliott/tests/test_find_builds_cli.py
  elliott/tests/test_konflux_release_cli.py
  elliott/tests/test_snapshot_cli.py
Labels: approved, lgtm

#1689 Init build_id in RhcosBuildInspector
  artcommon/artcommonlib/rhcos.py
  doozer/doozerlib/cli/inspect_stream.py
  doozer/doozerlib/rhcos.py
Labels: approved, lgtm, tide/merge-method-squash

#1690 Fix assembly merger in prepare-release
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: tide/merge-method-squash

#1691 Fix advisory finder attach-cv-flaws
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
Labels: approved, lgtm

#1693 Fix non-layered-rhcos detection
  doozer/doozerlib/rhcos.py
Labels: approved, lgtm

#1687 Refactor devcontainer setup for improved environment configuration
  .devcontainer/Containerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yaml
Labels: lgtm

#1696 Fix the [NO CHANGES] title update in ocp4-scan
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm

#1699 Do not dump html as part of jira search fails
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm, tide/merge-method-squash

#1702 Fix scan-sources
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/rhcos.py
Labels: approved, lgtm

#1483 Add awscli to pyartcd requirements
  pyartcd/requirements.txt
Labels: approved, tide/merge-method-squash

#1705 ART-13013 Move art-notify to pyartcd
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/pipelines/art_notify.py
  pyartcd/requirements.txt
Labels: lgtm

#1704 [Konflux] Add required labels for OLM bundles
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: approved, lgtm

#1708 [Konflux] Fix images-mirror-set to include the bundle itself
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/tests/backend/test_konflux_fbc.py
Labels: approved, lgtm

#1706 Reset rebase fail counters when rebase succeeds
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved

#1717 Enable --dump in watch release cli
  doozer/doozerlib/backend/konflux_client.py
  elliott/elliottlib/cli/konflux_release_cli.py
  elliott/elliottlib/cli/konflux_release_watch_cli.py
  elliott/elliottlib/cli/snapshot_cli.py
  elliott/tests/test_konflux_release_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1710 [Konflux] Use bundle delivery repo specified in ocp-build-data
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/image.py
  doozer/tests/backend/test_konflux_fbc.py
Labels: approved, lgtm

#1714 Add defensive checks for lockfile generation preconditions
  doozer/doozerlib/image.py
  doozer/doozerlib/lockfile.py
  doozer/tests/test_lockfile.py
Labels: approved, lgtm

#1711 ART-13070 gen-assembly: populate shipment advisories placeholders for Konflux
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/tests/cli/test_gen_assembly.py
Labels: approved, lgtm

#1727 Improve(exectools): resolve event loop binding bug in limit_concurrency decorator
  artcommon/artcommonlib/exectools.py
Labels: lgtm

#1737 Revert "Add skip_prepare_release param to the pipeline class"
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#1740 Fix major minor patch for ec and rcs
  elliott/elliottlib/runtime.py
  elliott/tests/test_runtime.py
Labels: lgtm

#1741 Make elliott brew event aware for Konflux assemblies
  artcommon/artcommonlib/assembly.py
  artcommon/artcommonlib/metadata.py
  artcommon/tests/test_assembly.py
  doozer/doozerlib/runtime.py
  elliott/elliottlib/brew.py
  elliott/elliottlib/runtime.py
Labels: approved, lgtm

#1742 Make git dir explicit
  doozer/doozerlib/backend/rebaser.py
Labels: approved

#1747 feat(telemetry): add comprehensive OpenTelemetry spans for async rebase operations
  doozer/doozerlib/backend/build_repo.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/lockfile.py
Labels: approved, lgtm

#1753 Support tools in shipment schema
  elliott/elliottlib/shipment_model.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
Labels: approved, lgtm

#1755 golang sweep: Tell which image is problem
  elliott/elliottlib/util.py
Labels: approved, lgtm

#1756 feat: enhance async command execution telemetry and tracing
  artcommon/artcommonlib/exectools.py
  artcommon/tests/test_exectools.py
  doozer/doozerlib/cli/images_konflux.py
Labels: approved, lgtm
