Repository openshift-eng/art-tools, pull requests merged in 2025-03, with the labels that each got.

#1397 Add Konflux specific build-sync lock
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1400 Fix upstream url for rpms
  doozer/doozerlib/cli/rpms.py
Labels: approved, lgtm

#1402 Do not clone distgits for Konflux
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#1394 artcommon: Update Konflux DB classes
  artcommon/artcommonlib/constants.py
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: lgtm

#1401 search_builds_by_fields(): match against multiple values
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1338 ART-12049 Consolidate metadata classes
  artcommon/artcommonlib/brew.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/metadata.py
  artcommon/artcommonlib/util.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/brew.py
  doozer/doozerlib/cli/config.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/doozerlib/config.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/olm/bundle.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/util.py
  doozer/tests/test_metadata.py
  elliott/elliottlib/brew.py
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/common.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/find_unconsumed_rpms.py
  elliott/elliottlib/cli/verify_cvp_cli.py
  elliott/elliottlib/metadata.py
  elliott/elliottlib/runtime.py
  elliott/tests/test_bzutil.py
  elliott/tests/test_metadata.py
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: do-not-merge/hold, tide/merge-method-squash

#1404 Fix lock name for Brew build-sync
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1406 release:gen-payload: never crash on emergency
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1405 Revert "ART-12049 Consolidate metadata classes"
  artcommon/artcommonlib/brew.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/metadata.py
  artcommon/artcommonlib/util.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/brew.py
  doozer/doozerlib/cli/config.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/doozerlib/config.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/olm/bundle.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/util.py
  doozer/tests/test_metadata.py
  elliott/elliottlib/brew.py
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/common.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/find_unconsumed_rpms.py
  elliott/elliottlib/cli/verify_cvp_cli.py
  elliott/elliottlib/metadata.py
  elliott/elliottlib/runtime.py
  elliott/tests/test_bzutil.py
  elliott/tests/test_metadata.py
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#1407 [konflux] disable ppc
  doozer/doozerlib/cli/scan_sources_konflux.py
  pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
Labels: approved, lgtm

#1408 ART-12049 (re)consolidate metadata libs
  artcommon/artcommonlib/brew.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/metadata.py
  artcommon/artcommonlib/util.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/brew.py
  doozer/doozerlib/cli/config.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/doozerlib/config.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/olm/bundle.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/util.py
  doozer/tests/test_metadata.py
  elliott/elliottlib/brew.py
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/common.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/find_unconsumed_rpms.py
  elliott/elliottlib/cli/verify_cvp_cli.py
  elliott/elliottlib/metadata.py
  elliott/elliottlib/runtime.py
  elliott/tests/test_bzutil.py
  elliott/tests/test_metadata.py
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm, tide/merge-method-squash

#1413 find-builds: Check for False instead of None
  elliott/elliottlib/brew.py
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#1415 Pass builds only if present
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#1414 uv run when running make tasks
  Makefile
  doozer/Makefile
  elliott/Makefile
  pyartcd/Makefile
Labels: approved, lgtm, tide/merge-method-squash

#1417 konflux arches for konflux build-sync
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1416 fix find builds issue
  artcommon/artcommonlib/metadata.py
  elliott/elliottlib/brew.py
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#1420 [ART-11745] scan-sources scan for RPM changes
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/konflux/package_rpm_finder.py
  doozer/doozerlib/build_info.py
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1422 images:health look back to latest 90 days
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#1424 Set cachito as explicit default for osbs builds
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#1428 Include shipped nvrs when searching for microshift
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm, tide/merge-method-squash

#1364 Konflux: Add beta:fbc:rebase verb to rebase FBC
  doozer/doozerlib/backend/build_repo.py
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/fbc.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/constants.py
  doozer/tests/backend/test_konflux_fbc.py
Labels: approved, lgtm

#1399 Fix image component for Konflux builds
  artcommon/artcommonlib/metadata.py
  artcommon/artcommonlib/runtime.py
  elliott/tests/test_imagecfg.py
Labels: approved, lgtm, tide/merge-method-squash

#1403 Add beta:fbc:build verb to build FBC segments
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/fbc.py
  doozer/doozerlib/constants.py
  doozer/tests/backend/test_konflux_fbc.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: approved, lgtm

#1425 [konflux] scan-sources look at extra_packages
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1426 [konflux] add a mass rebuild lock
  pyartcd/pyartcd/locks.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#1378 ART-12049 Elliott can create Konflux Snapshots
  artcommon/artcommonlib/konflux/konflux_db.py
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/images_konflux.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/find_konflux_builds_cli.py
  elliott/elliottlib/cli/snapshot_cli.py
  elliott/functional_tests/test_snapshot.py
  elliott/tests/test_snapshot_cli.py
Labels: approved, lgtm

#1423 Fix some broken tests for exectools
  artcommon/tests/test_exectools.py
Labels: approved, lgtm

#1431 [konflux] Update title for mass rebuilds
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1432 [temp][konflux] disable rebuilds on config changes
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1393 pyartcd: Add build-fbc job to rebase and build FBC
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/constants.py
  pyartcd/pyartcd/pipelines/build_fbc.py
Labels: approved, lgtm

#1392 pyartcd: Add fbc-import-from-index job
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/pipelines/fbc_import_from_index.py
Labels: approved, lgtm

#1435 Fix build-microshift job
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#1436 build-microshift: Don't ping release artists
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#1433 Fix scan-sources config changes check
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/doozerlib/image.py
Labels: approved, lgtm

#1439 Increase jenkins client timeout
  pyartcd/pyartcd/jenkins.py
Labels: approved, lgtm

#1440 [konflux] add -container while searching for brew builds
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1441 Doozer: Additional auth fix for FBC import
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/opm.py
  doozer/tests/test_opm.py
Labels: approved, lgtm

#1442 Konflux: only scan 4.19
  pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan_konflux.py
Labels: approved, lgtm

#1418 [ART-11902] konflux prefetch support
  artcommon/artcommonlib/util.py
  artcommon/tests/test_cachito.py
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/rebaser.py
  doozer/tests/backend/test_konflux_cachi2.py
Labels: approved, lgtm, tide/merge-method-squash

#1443 Revert "Konflux: only scan 4.19"
  pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan_konflux.py
Labels: approved, lgtm

#1444 [konflux] build-sync: re-enable a few assembly issues checks
  artcommon/artcommonlib/konflux/package_rpm_finder.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/build_info.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/test_assembly_inspector.py
Labels: approved, lgtm

#1447 Run mirror_payload_content() inside an async loop for concurrency
  doozer/doozerlib/cli/release_gen_payload.py
Labels: lgtm

#1445 elliott snapshot get
  elliott/elliottlib/cli/snapshot_cli.py
  elliott/functional_tests/test_snapshot.py
  elliott/tests/test_snapshot_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1448 ocp4-konflux: sync payloads for OCP >= 4.17
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1449 Also provide previous libreswan build
  pyartcd/pyartcd/plashets.py
Labels: approved

#1450 Restrict rebuilding same nvr in konflux
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1452 [ART-12120][konflux] root permissions required for repo management
  doozer/doozerlib/backend/rebaser.py
  doozer/tests/backend/test_konflux_cachi2.py
  doozer/tests/backend/test_rebaser.py
Labels: approved, lgtm, tide/merge-method-squash

#1457 merge konflux config before rebase
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1459 [TEMP] Disable RPM check until pulp is up again
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#1460 Revert "[TEMP] Disable RPM check until pulp is up again"
  doozer/doozerlib/cli/scan_sources.py
Labels: approved, lgtm

#1462 [konflux] merge the complete konflux config stanza when rebasing
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1464 [konflux] gen-payload: disable issue check for installed RPMs
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1469 [konflux] fix yum line rebase
  doozer/doozerlib/backend/rebaser.py
  doozer/tests/backend/test_rebaser.py
Labels: approved, lgtm

#1467 [konflux] sync private builds
  artcommon/artcommonlib/konflux/konflux_db.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm

#1468 FIx installed RPMs check for Konflux
  artcommon/artcommonlib/konflux/package_rpm_finder.py
  doozer/doozerlib/build_info.py
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1454 Do not warn about unfound builds
  artcommon/artcommonlib/konflux/konflux_db.py
Labels: approved, lgtm

#1474 [konflux] sync multiarch payloads
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1398 pin-builds cli
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/release_util.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/gen_assembly_helper.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/pin_builds_cli.py
  elliott/tests/test_pin_builds_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1478 [konflux] use force for git add
  doozer/doozerlib/backend/build_repo.py
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm, do-not-merge/hold, tide/merge-method-squash

#1466 [ART-12287] Update rhcos job to support target job name
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, lgtm, tide/merge-method-squash

#1480 [konflux] append .0 for go version
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1446 [konflux] fix component_name
  artcommon/artcommonlib/metadata.py
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm
