Repository openshift-eng/art-tools, pull requests merged in 2025-04, with the labels that each got.

#1479 build-fbc: Push to a dedicated quay repo
  doozer/doozerlib/cli/fbc.py
  doozer/doozerlib/constants.py
Labels: lgtm

#1475 ART-9439 - fixes after rebase
  doozer/doozerlib/cli/release_gen_payload.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#1486 Pin rhcos at the right level
  artcommon/artcommonlib/exectools.py
  artcommon/artcommonlib/lock.py
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  elliott/elliottlib/cli/pin_builds_cli.py
  elliott/tests/test_pin_builds_cli.py
Labels: approved, lgtm

#1488 [konflux] update UI url
  doozer/doozerlib/constants.py
Labels: approved, lgtm

#1487 [konflux] fix typo
  doozer/doozerlib/cli/fbc.py
  doozer/doozerlib/constants.py
Labels: approved, lgtm

#1491 [konflux] update UI url generation
  doozer/doozerlib/backend/konflux_client.py
  doozer/tests/backend/test_konflux_client.py
Labels: approved, lgtm

#1493 [konflux] build-sync: enable check RHCOS consistency
  artcommon/artcommonlib/konflux/package_rpm_finder.py
  doozer/doozerlib/build_info.py
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved

#1496 Sync only x86_64 for 4.12 and 4.13
  pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
Labels: approved, lgtm

#1497 Remove -container from search for konflux builds
  elliott/elliottlib/cli/snapshot_cli.py
Labels: approved, lgtm

#1495 [konflux] gen-payload: enable all checks
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1500 [konflux] build-sync: look at konflux arches in group config
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#1503 Add shipment schema and validation
  Makefile
  elliott/elliottlib/shipment_model.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
  ocp-build-data-validator/validator/schema/__init__.py
  ocp-build-data-validator/validator/schema/shipment_schema.py
  ocp-build-data-validator/validator/support.py
Labels: approved, tide/merge-method-squash

#1507 ART-12288: trigger node image job for 4.19
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: approved, lgtm, jira/valid-reference

#1502 [konflux] let doozer get-nightlies look at Konflux payloads
  doozer/doozerlib/cli/get_nightlies.py
  doozer/doozerlib/runtime.py
Labels: approved, lgtm

#1506 [konflux] fix sast bug
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1509 [konflux] more memory for sast task
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1513 ART-12585 Make cachito version configurable
  doozer/doozerlib/distgit.py
Labels: approved, lgtm

#1512 Register and check stream aliases
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm, tide/merge-method-squash

#1508 Manually install golang 1.23.0
  art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
Labels: approved, lgtm

#1515 Konflux: Change how FBC build record is stored
  doozer/doozerlib/backend/konflux_fbc.py
Labels: approved, lgtm

#1473 Use p2/p3 flags for Konflux releases
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/build_status_detector.py
  doozer/doozerlib/build_visibility.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/rpm_builder.py
  doozer/doozerlib/util.py
  doozer/tests/test_build_status_detector.py
  doozer/tests/test_build_visibility.py
  doozer/tests/test_rpm_builder.py
  doozer/tests/test_util.py
Labels: approved, lgtm

#1518 Make private builds process more robust
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/build_status_detector.py
  doozer/doozerlib/build_visibility.py
  doozer/doozerlib/cli/config_plashet.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/rpm_builder.py
  doozer/doozerlib/util.py
  doozer/tests/test_build_status_detector.py
  doozer/tests/test_build_visibility.py
  doozer/tests/test_rpm_builder.py
  doozer/tests/test_util.py
Labels: approved, lgtm

#1520 extract binary and siging for hotfix
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#1498 ART-12288: Support new rhcos node image and extensions
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/rhcos.py
  doozer/tests/cli/test_scan_sources.py
  doozer/tests/test_rhcos.py
Labels: approved, lgtm, jira/valid-reference

#1523 [konflux] append .0 for go version
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1522 Support multiple target releases for same MAJOR.MINOR
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/tests/test_util.py
Labels: approved, lgtm

#1521 Bring back Slack reporting to quay-doomsday-backup
  pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
Labels: approved, lgtm

#1455 Konflux - elliott release new
  artcommon/artcommonlib/constants.py
  artcommon/artcommonlib/gitdata.py
  artcommon/artcommonlib/util.py
  elliott/elliottlib/cli/common.py
  elliott/elliottlib/cli/konflux_release_cli.py
  elliott/elliottlib/cli/snapshot_cli.py
  elliott/elliottlib/runtime.py
  elliott/elliottlib/shipment_model.py
  elliott/tests/test_konflux_release_cli.py
  elliott/tests/test_snapshot_cli.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
Labels: approved, lgtm, tide/merge-method-squash

#1504 elliott shipment init
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/shipment_cli.py
  elliott/elliottlib/shipment_model.py
Labels: lgtm

#1526 [Konflux] Add NVR label to FBC artifacts
  doozer/doozerlib/backend/konflux_fbc.py
Labels: approved, lgtm

#1531 Enable rhel10 plashets
  pyartcd/pyartcd/plashets.py
Labels: approved, lgtm

#1534 [konflux] go version patch only for 1.22+
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1540 Always clean the doomsday pipeline workspace no matter the result
  pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
Labels: approved, lgtm

#1543 Fix pyartcd.util.branch_arches()
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#1544 ocp4 build all fix
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#1541 [Konflux] Create ImageDigestMirrorSet for FBC EC verification
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/tests/backend/test_konflux_fbc.py
Labels: lgtm

#1532 Standard assemblies can have permits sometimes
  artcommon/artcommonlib/assembly.py
Labels: approved, lgtm

#1527 [konflux] network_mode group config
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/metadata.py
  doozer/tests/backend/test_rebaser.py
  doozer/tests/test_metadata.py
Labels: approved, lgtm, tide/merge-method-squash

#1545 Revert "Revert "ART-12288: Support new rhcos node image and extensions""
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/rhcos.py
  doozer/tests/cli/test_scan_sources.py
  doozer/tests/test_rhcos.py
Labels: approved, lgtm, jira/valid-reference

#1551 Fix modification error
  doozer/doozerlib/source_modifications.py
Labels: approved, lgtm

#1554 trigger node build for 4.20
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#1555 Revert sbom package construction
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1559 Add liveID in shipment config
  Makefile
  elliott/elliottlib/shipment_model.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
Labels: approved, lgtm

#1560 Retry 502 times
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1561 Fix pyartcd logging bug
  pyartcd/pyartcd/runtime.py
Labels: approved, lgtm

#1562 Revert "ART-12600: use group config to check layered rhcos"
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/rhcos.py
Labels: jira/valid-reference

#1557 konflux SA override update
  doozer/doozerlib/backend/konflux_client.py
Labels: lgtm

#1564 ART-12600: use group config to check layered rhcos
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/rhcos.py
Labels: approved, lgtm, jira/valid-reference

#1565 Bump retries for multi payload creation
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1558 scan sources rebuild if hermetic
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: lgtm
