Repository openshift-eng/art-tools, pull requests merged in 2025-08, with the labels that each got.

#1863 Fix microshift pipeline
  elliott/elliottlib/cli/find_builds_cli.py
  pyartcd/pyartcd/util.py
Labels: approved, lgtm

#1865 ART-13935 scan-sources-konflux: also output RHCOS and RPMs changes
  doozer/doozerlib/cli/scan_sources_konflux.py
  pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
Labels: lgtm, tide/merge-method-squash

#1844 doozer images:show-ancestors
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/images.py
  doozer/tests/cli/test_images.py
Labels: lgtm

#1852 WIP translate delivery repo name to component name
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/elliottlib/cli/find_bugs_cli.py
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/tests/test_bzutil.py
  elliott/tests/test_find_bugs_sweep_cli.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
Labels: do-not-merge/work-in-progress

#1872 fix gen assembly
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: approved, lgtm

#1874 [Konflux] Fix FBC CSV metadata parsing and logo bootstrapping
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/util.py
  doozer/tests/backend/test_konflux_fbc.py
Labels: approved, lgtm

#1875 [Konflux] fbc:rebase: Always re-generate catalog.Dockerfile
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/tests/backend/test_konflux_fbc.py
Labels: approved, lgtm

#1866 feat(rebaser): add generic artifact validation for hermetic builds
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1878 Fix promote
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
Labels: lgtm

#1883 populate 4.19 nightlies with konflux builds
  artcommon/artcommonlib/constants.py
Labels: approved, lgtm

#1888 tag bootc pullspec to tag
  artcommon/artcommonlib/util.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
Labels: approved, lgtm

#1887 attach-cve-flaws first-fix filtering: Tweak GA detection logic
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/shipment_model.py
  elliott/tests/test_bzutil.py
  elliott/tests/test_konflux_release_cli.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1889 tag konflux builds by tag
  artcommon/artcommonlib/util.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
Labels: approved, lgtm, tide/merge-method-squash

#1828 elliott verify-conforma
  artcommon/artcommonlib/exectools.py
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/conforma_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1893 Update ocp-build-data after MR is created
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
  pyartcd/tests/pipelines/test_prepare_release_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1897 ART-13997 Construct full advisory id from shipment
  elliott/elliottlib/shipment_utils.py
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm, tide/merge-method-squash

#1899 promote-assembly: Don't fail if jira subtask is missing
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm

#1906 Update assembly schema to account for prerelease_permits
  ocp-build-data-validator/validator/json_schemas/assembly.schema.json
  ocp-build-data-validator/validator/json_schemas/permits.schema.json
Labels: lgtm

#1923 Update Jenkins title when building all RPMs
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1926 fix ocp4_scan_konflux remove clone distgit for konflux
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1913 ART-14002 remove date parameter
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1933 Fix RPM part in ocp4{-konflux} title on Jenkins
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1936 Konflux: acquire the mass rebuild lock before rebasing images
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1940 ART-12601 Forbid group! config which breaks the assembly group config override
  ocp-build-data-validator/validator/schema/releases_schema.py
Labels: approved, lgtm

#1941 Handle istag with null annotations when checking number of accepted multi nightlies
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1942 also get inflight for konflux release
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#1943 Skip non-nightly tags when searching for last nightly
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/tests/cli/test_gen_payload.py
Labels: approved, lgtm

#1945 Support art prefix for .repo files in brew rebase
  doozer/doozerlib/coverity.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/osbs2_builder.py
  doozer/tests/test_osbs2.py
  pyartcd/pyartcd/pipelines/rebuild.py
Labels: approved, lgtm, tide/merge-method-squash

#1950 Let oc login into the QCI registry
  pyartcd/pyartcd/oc.py
  pyartcd/pyartcd/pipelines/build_microshift.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: lgtm

#1948 Add mirroring to quay.io/openshift/ci (QCI) to images that should be used in CI
  doozer/doozerlib/cli/images_streams.py
Labels: approved, lgtm
