Repository openshift-eng/art-tools, pull requests merged in 2025-07, with the labels that each got.

#1729 Add tests for update_build_data in PrepareReleasePipeline
  pyartcd/tests/pipelines/test_prepare_release.py
Labels: approved, lgtm, tide/merge-method-squash

#1761 Skip snapshot if builds are not found
  elliott/elliottlib/cli/konflux_release_cli.py
  elliott/elliottlib/cli/snapshot_cli.py
  elliott/elliottlib/shipment_utils.py
  elliott/tests/test_shipment_utils.py
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1748 ART-12052 Elliott attach-cve-flaws for Konflux
  elliott/elliottlib/bzutil.py
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/elliottlib/shipment_utils.py
  elliott/tests/test_attach_cve_flaws_cli.py
  elliott/tests/test_shipment_utils.py
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1769 Konflux commands should default to build-system konflux
  elliott/elliottlib/cli/common.py
  elliott/elliottlib/cli/konflux_release_cli.py
  elliott/elliottlib/cli/konflux_release_watch_cli.py
  elliott/elliottlib/cli/shipment_cli.py
  elliott/elliottlib/cli/snapshot_cli.py
  elliott/elliottlib/runtime.py
  elliott/tests/test_konflux_release_cli.py
Labels: approved, lgtm

#1770 Remove alias from tools
  elliott/elliottlib/shipment_model.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
Labels: approved, lgtm

#1777 Start reporting konflux build failures publicly
  artcommon/artcommonlib/constants.py
  pyartcd/pyartcd/pipelines/images_health.py
Labels: approved, lgtm

#1776 ART-13331 Implement verify-payload for Konflux shipments
  elliott/elliottlib/cli/__main__.py
  elliott/elliottlib/cli/verify_payload.py
  elliott/elliottlib/util.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm, tide/merge-method-squash

#1783 ocp4-scan: skip brew build-sync for 4.20
  pyartcd/pyartcd/pipelines/ocp4_scan.py
Labels: lgtm

#1785 Tweak component name parsing from url
  artcommon/artcommonlib/konflux/konflux_build_record.py
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  elliott/elliottlib/cli/snapshot_cli.py
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1788 Konflux object date to microsecond precision
  artcommon/artcommonlib/util.py
Labels: approved, lgtm

#1797 Konflux assemblies should not reference advisories handled by shipment
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: lgtm

#1791 ART-13350 prepare-release-konflux creates jira ticket
  pyartcd/pyartcd/jira_client.py
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
  pyartcd/tests/pipelines/test_prepare_release_konflux.py
Labels: approved, lgtm

#1803 fix lint
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1805 ART-13270 Use build_component field in snapshot creation
  artcommon/artcommonlib/konflux/konflux_build_record.py
  elliott/elliottlib/cli/snapshot_cli.py
Labels: approved, lgtm

#1808 Update promote.py to remove check of subtask "notify to qe"
  pyartcd/pyartcd/pipelines/promote.py
Labels: approved, lgtm, tide/merge-method-squash

#1792 Konflux: Use multiple components for FBC
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/tests/backend/test_konflux_fbc.py
Labels: approved, lgtm

#1813 Support alt for multiple delivery repos when creating snapshot
  elliott/elliottlib/cli/snapshot_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1793 ART-13271 create rpm advisory in prepare release konflux
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
  pyartcd/tests/pipelines/test_prepare_release_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1815 Validate shipment snapshot applications
  elliott/elliottlib/shipment_model.py
  elliott/tests/test_konflux_release_cli.py
  elliott/tests/test_shipment_model.py
Labels: approved, lgtm, tide/merge-method-squash

#1818 [konflux] network_mode add to validator
  ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json
Labels: lgtm

#1819 Fix bundle nvr in record.log
  doozer/doozerlib/backend/konflux_olm_bundler.py
Labels: approved, lgtm

#1820 olm_bundle_konflux triggers build-fbc job
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/olm_bundle_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1765 Use safe formatting when loading template
  artcommon/artcommonlib/gitdata.py
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm, do-not-merge/hold, tide/merge-method-squash

#1829 [konflux-release] Only allow live_id for prod
  elliott/elliottlib/cli/konflux_release_cli.py
  elliott/tests/test_konflux_release_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1814 Do not report health of disabled images in konflux
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#1824 Fix Doozer unit test mocks
  doozer/tests/test_lockfile.py
Labels: approved, lgtm

#1825 [Konflux] Fix minor issues in KonfluxClient
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1831 feat(rpm-lockfile): add configurable parent exclusion for lockfile RPM collection
  doozer/doozerlib/image.py
  doozer/tests/test_image.py
  ocp-build-data-validator/tests/test_schema/test_image_schema.py
  ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json
Labels: approved, lgtm

#1832 [Konflux] FBC: Reset to prod index before build
  doozer/doozerlib/cli/fbc.py
  doozer/tests/cli/test_fbc.py
  pyartcd/pyartcd/pipelines/build_fbc.py
Labels: approved, lgtm

#1834 If shipment is shipped exit gracefully with warning
  elliott/elliottlib/cli/konflux_release_cli.py
  elliott/tests/test_konflux_release_cli.py
Labels: approved, lgtm

#1835 ART-13868: tag latest fbc builds with version
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/tests/backend/test_konflux_fbc.py
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1838 Sort builds when creating snapshot
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, lgtm

#1839 Set MR to draft in prepare pipeline
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, lgtm

#1841 allow konflux re-release for non-prod
  elliott/elliottlib/cli/konflux_release_cli.py
  elliott/tests/test_konflux_release_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1842 ART-13339: sync bundles to art-images-share
  doozer/doozerlib/backend/konflux_olm_bundler.py
Labels: lgtm, jira/valid-reference

#1848 Inject build-repo in prep
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
  pyartcd/tests/pipelines/test_prepare_release_konflux.py
Labels: approved, lgtm

#1850 Better prep error handling
  doozer/doozerlib/cli/fbc.py
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, do-not-merge/hold, tide/merge-method-squash

#1806 [Konflux] Add doozer verb to build stage operator index
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/cli/fbc.py
  doozer/doozerlib/runtime.py
  doozer/requirements.txt
  doozer/tests/backend/test_konflux_fbc.py
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/pipelines/build_merged_fbc.py
Labels: approved, lgtm

#1836 ART-3761 ADD release_date in gen-assembly
  doozer/doozerlib/cli/release_gen_assembly.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm, tide/merge-method-squash

#1857 trigger konflux build-sync if build-system is konflux
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm

#1794 [Konflux] Simplify fbc:import
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/cli/fbc.py
  doozer/doozerlib/opm.py
  doozer/tests/backend/test_konflux_fbc.py
  doozer/tests/cli/test_fbc.py
  doozer/tests/test_opm.py
Labels: approved, lgtm
