Repository openshift-eng/art-tools, pull requests merged in 2025-05, with the labels that each got.

#1576 Disable scan_network_mode_changes()
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1575 [Snyk] Security upgrade setuptools from 40.5.0 to 78.1.1
  doozer/requirements.txt
Labels: approved, lgtm

#1578 fix nvr issue
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1556 [konflux] gen-payload for named assemblies
  artcommon/artcommonlib/assembly.py
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/konflux/package_rpm_finder.py
  artcommon/artcommonlib/metadata.py
  artcommon/tests/test_konflux_db.py
  doozer/doozerlib/brew.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/runtime.py
  doozer/doozerlib/util.py
  doozer/requirements.txt
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/cli/test_rpms_build.py
  doozer/tests/test_osbs2.py
  doozer/tests/test_rpmcfg.py
Labels: approved, lgtm

#1580 Fallback to brew basis event
  doozer/doozerlib/runtime.py
Labels: approved, lgtm

#1579 Replace flake8 with ruff lint
  .git-blame-ignore-revs
  Makefile
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_exectools.py
  doozer/doozerlib/backend/konflux_fbc.py
  doozer/doozerlib/brew.py
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/images.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/rpms.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/doozerlib/dblib.py
  doozer/doozerlib/image.py
  doozer/doozerlib/util.py
  doozer/requirements-dev.txt
  doozer/tests/backend/test_konflux_cachi2.py
  doozer/tests/test_distgit/support.py
  doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
  doozer/tox.ini
  elliott/elliottlib/tarball_sources.py
  elliott/elliottlib/util.py
  elliott/pyproject.toml
  elliott/tests/test_find_bugs_kernel_clones_cli.py
  elliott/tests/test_verify_attached_operators.py
  elliott/tox.ini
  ocp-build-data-validator/requirements-dev.txt
  ocp-build-data-validator/tox.ini
  pyartcd/pyartcd/pipelines/prepare_release.py
  pyartcd/requirements-dev.txt
  pyartcd/tox.ini
  ruff.toml
  tox.ini
Labels: approved, lgtm, tide/merge-method-squash

#1583 Enable find-builds for konflux
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/tests/test_find_builds_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1586 OCPBUGS-55823: clean up temporary files
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/constants.py
  doozer/tests/backend/test_rebaser.py
Labels: approved, lgtm, jira/invalid-bug, jira/valid-reference

#1589 download_file_from_github(): require a session param
  artcommon/artcommonlib/util.py
  doozer/doozerlib/cli/images_okd.py
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: lgtm

#1591 Enable defaults for shipment config init
  artcommon/artcommonlib/gitdata.py
  elliott/elliottlib/cli/shipment_cli.py
  elliott/elliottlib/runtime.py
Labels: approved, lgtm, tide/merge-method-squash

#1588 Deprecate bugzilla in bug sweep
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/tests/test_find_bugs_sweep_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1595 [konflux] slsa attestation raise exception
  artcommon/artcommonlib/util.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: lgtm

#1597 Add future to artcommon requirements
  artcommon/requirements.txt
Labels: approved, lgtm

#1598 use split instead of strip
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1600 replace rstrip with removesuffix
  pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
Labels: approved, lgtm

#1596 [konflux] Re-introduce the -container suffix in NVRs
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
  elliott/elliottlib/cli/snapshot_cli.py
Labels: lgtm

#1601 Fix konflux OLM bundle builds
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: approved, lgtm

#1604 ART-11852 directly create advisory
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#1605 add fallback for konflux builds
  artcommon/artcommonlib/konflux/konflux_db.py
Labels: approved, lgtm

#1573 ART-12761: docs workflow update
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/elliottlib/cli/create_cli.py
  elliott/elliottlib/cli/shipment_cli.py
  elliott/elliottlib/runtime.py
  elliott/elliottlib/util.py
  elliott/tests/test_create_cli.py
  elliott/tests/test_runtime.py
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1608 ART-12702 support new rhcos build name
  artcommon/artcommonlib/rhcos.py
Labels: approved, lgtm

#1609 Sync konflux builds to default imagestream for 4.20
  artcommon/artcommonlib/constants.py
  doozer/doozerlib/cli/release_gen_payload.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm, tide/merge-method-squash

#1610 ART-12592 Set live_id in shipment release notes
  elliott/elliottlib/shipment_model.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
Labels: approved, lgtm

#1614 Fix ocp4 on rebase errors
  doozer/doozerlib/cli/images.py
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#1615 Fix elliott create cli
  doozer/requirements.txt
  elliott/pyproject.toml
  pyartcd/requirements.txt
Labels: approved

#1612 [Konflux] Fix Konflux bundle and FBC build
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1617 Fix RHSA synopsis
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
Labels: approved, lgtm

#1619 ART-12761: update docs workflow
  elliott/elliottlib/cli/attach_cve_flaws_cli.py
  elliott/tests/test_attach_cve_flaws_cli.py
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1611 Application label in Release
  elliott/elliottlib/cli/konflux_release_cli.py
  elliott/tests/test_konflux_release_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1620 added missing arguments for categorize_bugs_by_type
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
  elliott/elliottlib/cli/verify_attached_bugs_cli.py
  elliott/tests/test_verify_attached_bugs_cli.py
Labels: approved, lgtm, tide/merge-method-squash

#1533 Elliott: Respect `art:pscomponent:` label for new style trackers
  elliott/elliottlib/bzutil.py
Labels: approved, lgtm

#1618 ART-12941 Correctly fetch attached builds and filter
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/errata_async.py
Labels: approved, lgtm

#1621 konflux image builder: set the right component name in record.log
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: approved

#1623 Fix build microshift
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: approved, lgtm

#1622 shipment pipeline update
  elliott/elliottlib/shipment_model.py
  elliott/tests/test_konflux_release_cli.py
  ocp-build-data-validator/validator/json_schemas/shipment.schema.json
Labels: approved, lgtm, tide/merge-method-squash

#1624 Konflux: Fix bundle build again
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: approved, lgtm

#1627 [konflux] scan-sources: merge Konflux config if present before scan
  doozer/doozerlib/build_info.py
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1629 [Konflux] Remove _find_previous_versions from rebase
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1633 ART-12957: broken links in Slack message
  doozer/doozerlib/cli/images_health.py
  doozer/tests/cli/test_images_health.py
Labels: approved, lgtm, jira/valid-reference

#1631 log Release URL
  elliott/elliottlib/cli/konflux_release_cli.py
Labels: lgtm

#1632 ART-12117: migrate sbom type from cyclonedx to spdx
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: lgtm, tide/merge-method-squash, jira/valid-reference

#1634 Report on Konflux errors for 4.20
  pyartcd/pyartcd/pipelines/images_health.py
Labels: approved, lgtm, tide/merge-method-squash

#1636 [Konflux] Add request timeouts to all API calls
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1637 Bring back -container suffix in bundle build records
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: approved

#1641 [Konflux] Fix rebase error in bundle build
  doozer/doozerlib/backend/konflux_olm_bundler.py
Labels: approved, lgtm

#1642 Konflux: Fix NVR handling leftovers
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: approved, lgtm

#1645 Fix brew tag retrieval in doozer images:scan-fips
  doozer/doozerlib/cli/scan_fips.py
Labels: approved, lgtm

#1648 gen-assembly: fix yaml dump
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: approved, lgtm, tide/merge-method-squash

#1650 Add hermetic field in DB record
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
Labels: approved, lgtm

#1649 ART-13013 ocp4_konflux: store rebase failures in Redis
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1651 Elliott: Fix import error in unit tests
  elliott/tests/test_runtime.py
Labels: approved, lgtm

#1655 imagestream override konflux
  doozer/doozerlib/cli/release_gen_assembly.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, tide/merge-method-squash

#1546 ART-12697 Add prepare-release-konflux pipeline
  artcommon/artcommonlib/assembly.py
  artcommon/tests/test_assembly.py
  doozer/tests/backend/test_rebaser.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/errata_async.py
  elliott/elliottlib/shipment_model.py
  ocp-build-data-validator/validator/json_schemas/assembly_basis.schema.json
  ocp-build-data-validator/validator/json_schemas/assembly_group_config.schema.json
  pyartcd/config.example.toml
  pyartcd/pyartcd/__main__.py
  pyartcd/pyartcd/git.py
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
  pyartcd/requirements.txt
  pyartcd/tests/pipelines/test_prepare_release_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#1582 Update ruff rules
  ruff.toml
Labels: approved

#1658 Adjust build-sync for Konflux
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1661 Check group config for determining rhcos job name
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_scan.py
  pyartcd/pyartcd/util.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: approved, lgtm, tide/merge-method-squash
