Repository openshift-eng/art-tools, pull requests merged in 2025-02, with the labels that each got.

#1321 Raise for status build/rhcos
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, lgtm, tide/merge-method-squash

#1319 ART-11391 build-sync for konflux
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/build_info.py
  doozer/doozerlib/cli/inspect_stream.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
  doozer/tests/cli/test_gen_payload.py
  doozer/tests/cli/test_scan_sources.py
  doozer/tests/test_assembly_inspector.py
  doozer/tests/test_brew_inspector.py
  doozer/tests/test_image.py
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1322 build-sync: tag konflux builds on jenkins
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1323 Ignore invalid version-release rpms in rhcos
  doozer/doozerlib/rhcos.py
Labels: lgtm

#1325 exectools: print the command string instead of a list
  artcommon/artcommonlib/exectools.py
Labels: approved, lgtm

#1324 ART-11391 Trigger build-sync after ocp4-konflux
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/build_sync.py
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
  pyartcd/pyartcd/util.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: lgtm, tide/merge-method-squash

#1327 fix oc image info
  doozer/doozerlib/build_info.py
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1328 ocp4-konflux: fix parse arches from group config
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: lgtm

#1329 Remove stray quote from log
  artcommon/artcommonlib/exectools.py
Labels: approved, lgtm

#1337 Konflux: Fix race condition in KonfluxRebaser
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1339 [konflux] build/sync microshift-bootc location
  doozer/doozerlib/constants.py
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
Labels: approved

#1342 [konflux][ART-11576] refspec fix
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1347 [konflux] fix bootc
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
Labels: approved, lgtm

#1348 [konflux] use bigger IBM VM flavors
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1350 Reduce bigquery module logging verbosity
  artcommon/artcommonlib/bigquery.py
Labels: approved, lgtm

#1351 Improve prepare-release commands logging
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#1352 Report bugs to be checked in a thread
  pyartcd/pyartcd/pipelines/check_bugs.py
Labels: approved, lgtm

#1354 Enable mismatched siblings check for Konflux build-sync
  doozer/doozerlib/build_info.py
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1353 Fail build-sync for konflux in case of missing builds
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1357 microshift-buildc: bootc-pullspec.txt fixes
  pyartcd/pyartcd/pipelines/build_microshift_bootc.py
Labels: approved, lgtm

#1356 build-sync for konflux: apply imagestream annotations
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1358 [konflux] report rebase failures on Slack
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#1359 scan-sources-konflux: always search for RPM Brew builds in BigQuery
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1336 Fix bugs in update_golang pipeline
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm

#1363 Konflux: Use metadata.get_latest_build in bundle build
  doozer/doozerlib/cli/images_konflux.py
  pyartcd/pyartcd/pipelines/olm_bundle_konflux.py
Labels: approved, lgtm

#1365 Skip fetching cdn repos in dry-run mode
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#1366 Fix bundle build error and hermetic build config
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1367 elliott find-builds: skip builds that have no accepted brew tags
  elliott/elliottlib/cli/find_builds_cli.py
Labels: lgtm

#1368 Use correct params in cmd invoke
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#1369 Fix microshift rpm plashet product version
  pyartcd/pyartcd/plashets.py
Labels: approved, lgtm

#1370 ART-12118: Add TaskRun outcome & timing to bigquery
  artcommon/artcommonlib/constants.py
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/artcommonlib/konflux/konflux_db.py
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
Labels: jira/valid-reference

#1373 ART-12164 check cve tracker bug in included bug list
  elliott/elliottlib/cli/find_bugs_sweep_cli.py
Labels: approved, lgtm

#1374 Adding yarn package manager emulation mode for cachito
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1376 [konflux] tagging mode
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1377 Ensure waiting for pipelinerun provides periodic updates
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1379 ART-12161 Handle brew/konflux sync failures separately
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1381 fix pr cretion for golang-builder
  pyartcd/pyartcd/pipelines/update_golang.py
Labels: approved, lgtm, tide/merge-method-squash

#1355 ART-9439 - modifications in prepare-release
  doozer/doozerlib/cli/release_gen_payload.py
  pyartcd/pyartcd/pipelines/prepare_release.py
Labels: approved, lgtm

#1384 Add configurable timeouts to pipelineruns
  artcommon/artcommonlib/konflux/konflux_build_record.py
  artcommon/artcommonlib/util.py
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1387 Fix elliott functional tests
  Makefile
  elliott/functional_tests/constants.py
  elliott/functional_tests/test_change_state.py
  elliott/functional_tests/test_find_bugs_qe.py
  elliott/functional_tests/test_find_bugs_sweep.py
  elliott/functional_tests/test_find_builds.py
  elliott/functional_tests/test_get.py
  elliott/functional_tests/test_list.py
  elliott/functional_tests/test_poll_signed.py
  elliott/functional_tests/test_rpmdiff.py
  elliott/functional_tests/test_tarball_sources.py
  elliott/functional_tests/test_verify_attached_bugs.py
  elliott/functional_tests/test_verify_payload.py
Labels: approved, lgtm, tide/merge-method-squash

#1389 [konflux] remove unused code
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#1396 Fixing logging message
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1395 [konflux] random choice for ppc VM flavor
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm
