Repository openshift-eng/art-tools, pull requests merged in 2025-01, with the labels that each got.

#1244 [konflux] comment out cachito lines during rebase
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1247 ocp4-scan-konflux: use group defaults for rpms with no explicit targets
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: lgtm

#1248 [konflux] download yarn if missing, function refactor
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1250 [konflux] increase yarn install timeout
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1252 images-health: fix doozer output
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#1253 images-health: do not complain when latest green build is too old
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#1254 images-health follow-up
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#1255 rpms: add changelog section to specfiles if missing
  doozer/doozerlib/rpm_builder.py
Labels: approved, lgtm

#1257 [konflux] Fix scan arch changes
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: lgtm

#1233 ocp4: clean up sources at the end of the artcd pipeline
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
  pyartcd/pyartcd/runtime.py
  pyartcd/tests/pipelines/test_ocp4.py
Labels: approved, lgtm

#1152 Konflux: Add OLM bundle rebase/build support
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/artcommonlib/runtime.py
  artcommon/artcommonlib/util.py
  artcommon/tests/test_konflux_db.py
  doozer/doozerlib/backend/build_repo.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/cli/images_health.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/doozerlib/image.py
  doozer/doozerlib/source_resolver.py
  doozer/tests/backend/test_build_repo.py
  doozer/tests/backend/test_konflux_olm_bundler.py
  doozer/tests/cli/test_gen_payload.py
Labels: lgtm

#1256 ART-11063 scan-sources: get RPM commitish from latest distgit commit message
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1235 ART-11093 use group arches to get rhcos list
  doozer/doozerlib/cli/release_gen_assembly.py
Labels: approved, lgtm

#1258 [konflux] cachito fix
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1261 [konflux] cachito fix
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1264 Add Rayford to OWNERS
  OWNERS
Labels: approved, lgtm

#1263 Konflux: Use single-arch pipelinerun template to build OLM bundles
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/constants.py
  doozer/tests/backend/test_konflux_olm_bundler.py
  pyartcd/pyartcd/constants.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: lgtm

#1267 Rename medatata.get_latest_build into get_latest_brew_build
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/build_status_detector.py
  doozer/doozerlib/cli/olm_bundle.py
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/doozerlib/cli/release_gen_payload.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/distgit.py
  doozer/doozerlib/image.py
  doozer/doozerlib/metadata.py
  doozer/doozerlib/plashet.py
  doozer/tests/test_metadata.py
  doozer/tests/test_plashet.py
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#1268 Define common entrypoint for metadata.get_latest_build
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/cli/scan_sources.py
  doozer/doozerlib/metadata.py
Labels: approved, lgtm

#1269 build-sync: Do not fail early
  Makefile
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1276 Fix elliott find-builds
  elliott/elliottlib/cli/find_builds_cli.py
Labels: approved, lgtm

#1277 [konflux] do not use the -container suffix in the NVRs
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/konflux_olm_bundler.py
  doozer/tests/backend/test_konflux_olm_bundler.py
Labels: approved, lgtm

#1274 promote-assembly: retry on 502
  pyartcd/pyartcd/pipelines/promote.py
  pyartcd/tests/pipelines/test_promote.py
Labels: approved, lgtm

#1262 KonfluxDB: Always use timezone aware datetime objects
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: lgtm

#1270 Add CronJob triggering the FIPS pipeline to ArgoCD
  art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/cronjob.yaml
Labels: approved, lgtm

#1278 [ART-11306] Make quay-doomsday-backup async and send its results to Slack
  pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
  pyartcd/pyartcd/slack.py
Labels: approved, lgtm

#1284 Don't raise microshift advisory validation error for preGA assembly
  pyartcd/pyartcd/pipelines/build_microshift.py
Labels: tide/merge-method-squash

#1265 [Konflux] Add fbc:import command to create FBC from published index
  doozer/doozerlib/backend/build_repo.py
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/cli/__main__.py
  doozer/doozerlib/cli/fbc.py
  doozer/doozerlib/opm.py
  doozer/tests/cli/test_fbc.py
  doozer/tests/test_opm.py
Labels: lgtm

#1271 Define metadata.get_latest_konflux_build()
  artcommon/artcommonlib/konflux/konflux_db.py
  artcommon/tests/test_konflux_db.py
  doozer/doozerlib/cli/cli_opts.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/doozerlib/metadata.py
  pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
Labels: lgtm

#1280 [konflux] network modes
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1287 Differentiate between unviable and failed build-sync run in title
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: tide/merge-method-squash

#1272 Get latest k build follow up
  artcommon/artcommonlib/runtime.py
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/cli/__init__.py
  doozer/doozerlib/cli/images_konflux.py
  doozer/doozerlib/runtime.py
Labels: approved, lgtm

#1184 Deal with kernel stop ship tag better pre-GA
  artcommon/artcommonlib/assembly.py
  doozer/doozerlib/assembly_inspector.py
  pyartcd/pyartcd/pipelines/tag_rpms.py
Labels: approved, lgtm

#1291 Fix ocp4-scan-konflux
  pyartcd/pyartcd/jenkins.py
Labels: approved, lgtm

#1290 [ART-11852] add microshift flag for gen assembly job
  doozer/doozerlib/cli/release_gen_assembly.py
  doozer/tests/cli/test_gen_assembly.py
  pyartcd/pyartcd/pipelines/gen_assembly.py
Labels: approved, lgtm, tide/merge-method-squash

#1292 Revert "Revert "[konflux] network modes""
  doozer/doozerlib/backend/konflux_client.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1296 [konflux] persist images on quay repo
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1286 [konflux] ENV variables for cachito/cachi2 and network mode identifcation
  doozer/doozerlib/backend/rebaser.py
  doozer/doozerlib/distgit.py
Labels: lgtm, tide/merge-method-squash

#1298 Fix exclude-arch param in release:gen-payload
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1299 Update build-sync title before exiting
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1300 build-sync: fix dry-run logs
  pyartcd/pyartcd/pipelines/build_sync.py
Labels: approved, lgtm

#1304 [konflux] Build only for x86 for now
  doozer/doozerlib/cli/scan_sources_konflux.py
  pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
Labels: approved, lgtm

#1305 Define oc_image_info_show_multiarch()
  doozer/doozerlib/util.py
  doozer/tests/test_util.py
Labels: approved, lgtm

#1306 [konflux] update label to Empty
  doozer/doozerlib/backend/rebaser.py
Labels: lgtm

#1307 Olm bundle build db write fix
  doozer/doozerlib/cli/olm_bundle.py
Labels: approved, lgtm

#1310 Revert "Start RHCOS arch jobs earlier"
  pyartcd/pyartcd/pipelines/build_rhcos.py
Labels: approved, needs-ok-to-test, lgtm

#1308 Give oc_image_info() auth powers
  doozer/doozerlib/util.py
Labels: approved, lgtm

#1309 [find-bugs:golang] Validate cve_id is set or skip
  elliott/elliottlib/cli/find_bugs_golang_cli.py
Labels: approved, lgtm

#1311 disabled konflux_olm_bundle failed message for realease channels
  pyartcd/pyartcd/pipelines/olm_bundle_konflux.py
Labels: approved, lgtm

#1312 images:health exclude disabled images
  doozer/doozerlib/cli/images_health.py
Labels: approved, lgtm

#1314 [konflux] Merge konflux config before rebase
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1315 Fix update .dockerignore
  doozer/doozerlib/backend/rebaser.py
Labels: approved, lgtm

#1317 Run oc adm release new in sync mode
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm

#1318 Retry failed arch only
  doozer/doozerlib/cli/release_gen_payload.py
Labels: approved, lgtm
