Repository openshift-eng/art-tools, pull requests merged in 2025-09, with the labels that each got.

#1954 Fix ocp4 title and description; do not sweep unless needed
  pyartcd/pyartcd/pipelines/ocp4.py
Labels: approved, lgtm

#1955 Konflux scan-sources: fix RPM check
  doozer/doozerlib/cli/scan_sources_konflux.py
Labels: approved, lgtm

#1956 Check if Jenkins build path is not empty
  pyartcd/pyartcd/jenkins.py
Labels: approved, lgtm

#1961 images-health: purge Brew notifications
  pyartcd/pyartcd/pipelines/images_health.py
Labels: lgtm

#1973 jenkins.py: extract build params from URL
  pyartcd/pyartcd/jenkins.py
Labels: approved, lgtm

#1976 ART-14093 notify about mass rebuild start/end
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm

#2002 pin ghapi to 1.0.6
  doozer/requirements.txt
  pyartcd/requirements.txt
Labels: approved, lgtm

#2003 Revert "Revert "Add BuildDataLoader for loading configs from build data repo""
  artcommon/artcommonlib/assembly.py
  artcommon/artcommonlib/config/__init__.py
  doozer/doozerlib/assembly_inspector.py
  doozer/doozerlib/runtime.py
  elliott/elliottlib/cli/find_bugs_golang_cli.py
  elliott/elliottlib/cli/find_builds_cli.py
  elliott/elliottlib/cli/find_unconsumed_rpms.py
  elliott/elliottlib/runtime.py
Labels: do-not-merge/hold

#2013 Permit discrepancy for ose-aws-ecr-image-credential-provider
  doozer/doozerlib/assembly_inspector.py
Labels: approved, lgtm

#2018 Unconditionally run attach-cv-flaws
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
Labels: approved, lgtm

#2021 fail build if source image signature is missing
  artcommon/artcommonlib/util.py
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/doozerlib/cli/scan_sources_konflux.py
  doozer/tests/cli/test_scan_sources_konflux.py
Labels: approved, lgtm, tide/merge-method-squash

#2020 fix build priority bug
  doozer/doozerlib/backend/konflux_image_builder.py
Labels: approved, lgtm

#2034 Add resource for prefetch-dependencies step
  doozer/doozerlib/backend/konflux_client.py
Labels: approved, lgtm

#1932 Add 4.21 to active ocp versions
  artcommon/artcommonlib/constants.py
Labels: approved, lgtm

#2030 feat(konflux): add prerelease GPG check disable for RPM prefetch
  doozer/doozerlib/backend/konflux_image_builder.py
  doozer/tests/backend/test_konflux_cachi2.py
Labels: approved, lgtm

#2037 Revert "Commit builds for each shipment individually (#2010)"
  pyartcd/pyartcd/pipelines/prepare_release_konflux.py
  pyartcd/tests/pipelines/test_prepare_release_konflux.py
Labels: approved, lgtm

#2044 oadp auto trigger bundle and fbc
  pyartcd/pyartcd/jenkins.py
  pyartcd/pyartcd/pipelines/build_oadp.py
  pyartcd/pyartcd/pipelines/olm_bundle_konflux.py
Labels: lgtm

#2047 Do no spam about broken FBC
  pyartcd/pyartcd/pipelines/build_fbc.py
Labels: approved, lgtm

#2048 Do not store rebase failures for test assembly
  pyartcd/pyartcd/pipelines/ocp4.py
  pyartcd/pyartcd/pipelines/ocp4_konflux.py
Labels: approved, lgtm
